### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'encoding'

### ISSUE THREAD

**Issue by Heryx** [pyarchinit/pyarchinit#104]
Ciao ragazzi,

ho appena provato ad esportare il matrix dalla scheda us e mi fa questo errore:

`  File "C:\OSGEO4~1\apps\Python37\lib\site-packages\graphviz\_compat.py", line 43, in stderr_write_bytes
              encoding = sys.stderr.encoding or sys.getdefaultencoding()
             AttributeError: 'NoneType' object has no attribute 'encoding'
             ` 
Credo sia un problema legato a Graphviz, come risolvo?

**Comment by enzococca** [comment]
È un problema di graphviz python. Installa la versione dal mio github e
avvia qgis da amminist. Si chiederà di installare la versione 0.8.3.
Dovresti risolvere così il problema

Il giorno Sab 19 Gen 2019, 13:08 Giuseppe Guarino <notifications@github.com>
ha scritto:

**Comment by Heryx** [comment]
Ad ogni modo adesso funziona. Grazie Enzo

**Comment by enzococca** [comment]
Ti dava quell errore perchè non hai avviato da amministratore

Il giorno Sab 19 Gen 2019, 14:59 Giuseppe Guarino <notifications@github.com>
ha scritto:

**Comment by Heryx** [comment]
L'ho avviato da amministratore, ha installato aggiornato graphviz, però non VisVis
Come mai viene usata la libreria Visvis in pyarchinit?

**Comment by enzococca** [comment]
Sperimentale per la scheda di archeozoologia

Il giorno Sab 19 Gen 2019, 15:06 Giuseppe Guarino <notifications@github.com>
ha scritto:
