### ISSUE TITLE
Install error Mac Os Sierra 10.12.6

### ISSUE THREAD

**Issue by archeorosati** [pyarchinit/pyarchinit#12]
Errore nel processo di installazione su **Mac Os Sierra 10.12.6** su **QGIS3** mi segnala il seguente errore:

![schermata 2018-05-05 alle 12 39 31](https://user-images.githubusercontent.com/39003545/39662420-6fbfebc6-5061-11e8-8eec-0fb957169f6d.png)
![schermata 2018-05-05 alle 12 39 42](https://user-images.githubusercontent.com/39003545/39662424-7a20883c-5061-11e8-8586-06477e960d45.png)

**Comment by enzococca** [comment]
Quando ti da questo errore? Appena installi pyarchinit da zip?

Il Sab 5 Mag 2018, 12:40 archeorosati <notifications@github.com> ha scritto:

**Comment by archeorosati** [comment]
Si esatto vi mando gli screen di
![schermata 2018-05-05 alle 12 55 03](https://user-images.githubusercontent.com/39003545/39662578-18363e66-5064-11e8-9a4e-82229d40a601.png)
 come ci arrivo:
![schermata 2018-05-05 alle 12 53 47](https://user-images.githubusercontent.com/39003545/39662563-c5d9e370-5063-11e8-9d66-db42f68a18fa.png)
![schermata 2018-05-05 alle 12 54 39](https://user-images.githubusercontent.com/39003545/39662566-c83848e6-5063-11e8-9801-61a2f3f04196.png)
![schermata 2018-05-05 alle 12 54 50](https://user-images.githubusercontent.com/39003545/39662567-c93e204e-5063-11e8-814e-30676d23bed7.png)

**Comment by archeorosati** [comment]
[Risolto]
Ho installato da terminale i seguenti moduli che evidentemente non erano vermante presenti nel pacchetto del mio Qgi3:

pip3 install pyper
pip3 install graphviz
pip3 install sqlalchemy
pip3 install reportlab
pip3 install networkx
pip3 install matplotlib

![schermata 2018-05-05 alle 13 30 39](https://user-images.githubusercontent.com/39003545/39662843-8d8ba35a-5068-11e8-8c5e-cac9c616e33f.png)

Una domanda, quando installa sul Mac, dove installa? per provare le varie schede devo sostituire il db .sqlite...

**Comment by enzococca** [comment]
Nella tua home una cartella che si chiama pyarchinit. Denteo trovi le
cartelle dove ci sono le esportazioni

Il Sab 5 Mag 2018, 13:38 archeorosati <notifications@github.com> ha scritto:

**Comment by enzococca** [comment]
Il problema è probabilmente dello standalone di qgis del mac ma stiamo
risolvendo

Il Sab 5 Mag 2018, 13:38 archeorosati <notifications@github.com> ha scritto:

**Comment by slarosa** [comment]
@archeorosati ti va di fare un test con me?

Apri un terminale e digita ```python``` poi incolla qui l'output che ti da il comando. 
Fai lo stesso con ```python3```. Grazie.

**Comment by slarosa** [comment]
@archeorosati potresti fare una prova per capire se nell'ultima master il problema è stato risolto?

**Comment by archeorosati** [comment]
Ciao Salvatore, non avevo letto i messaggi precedenti, ora provo a fare il test scusami tanto!!!

**Comment by slarosa** [comment]
@archeorosati tranquillo, fai i test con l'ultimissima master.

**Comment by archeorosati** [comment]
ok disinstallo e vado

**Comment by archeorosati** [comment]
Allora il primo test che mi hai chiesto:
Scrivo `python` lui risponde così
```
Python 2.7.8 (v2.7.8:ee879c0ffa11, Jun 29 2014, 21:07:35) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
```

Esco dal terminale scrivo `python3`

Lui risponde: 

```
Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 03:03:55) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```
esco scrivo `which -a python python3`:
`/Library/Frameworks/Python.framework/Versions/2.7/bin/python
/usr/local/bin/python
/usr/bin/python
/Library/Frameworks/Python.framework/Versions/3.6/bin/python3
/usr/local/bin/python3
MacBook-Air-di-Paolo-2:~ paolorosati$ `
Ultimi passaggi richiesti:

```
[MacBook-Air-di-Paolo-2:~ paolorosati$ import sys
-bash: import: command not found
MacBook-Air-di-Paolo-2:~ paolorosati$ sys.path
-bash: sys.path: command not found
MacBook-Air-di-Paolo-2:~ paolorosati$ ]
```

**Comment by slarosa** [comment]
Grazie. Gli ultimi passaggi devi farli dalla console di QGIS .

**Comment by archeorosati** [comment]
```
>> which -a python python3
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/code.py", line 64, in runsource
    code = self.compile(source, filename, symbol)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/codeop.py", line 168, in __call__
    return _maybe_compile(self.compiler, source, filename, symbol)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/codeop.py", line 99, in _maybe_compile
    raise err1
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/codeop.py", line 87, in _maybe_compile
    code1 = compiler(source + "\n", filename, symbol)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/codeop.py", line 133, in __call__
    codeob = compile(source, filename, symbol, self.flags, 1)
  File "<input>", line 1
    which -a python python3
                  ^
SyntaxError: invalid syntax
import sys
sys.path
['/Users/paolorosati/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/gui/ui', '/Users/paolorosati/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/resources', '/Users/paolorosati/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/gui/ui', '/Users/paolorosati/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/resources', '/Users/paolorosati/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/gui/ui', '/Users/paolorosati/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/resources', '/Applications/QGIS3.app/Contents/MacOS/../Resources/python', '/Users/paolorosati/Library/Application Support/QGIS/QGIS3/profiles/default/python', '/Users/paolorosati/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins', '/Applications/QGIS3.app/Contents/MacOS/../Resources/python/plugins', '/Library/Frameworks/Python.framework/Versions/3.6/lib/python36.zip', '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6', '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/lib-dynload', '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages', '/Users/paolorosati/Library/Application Support/QGIS/QGIS3/profiles/default/python', '/Users/paolorosati/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master', '/Users/paolorosati/Desktop/Cartografia/Tibur pars altera', '/Users/paolorosati/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master', '/Users/paolorosati/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master']
```

**Comment by archeorosati** [comment]
Secondo test, ho disinstallato pyarchinit,
ho preso la nuova master, inserito la cartella .zip
cliccatto su installa, e si installa che è una meraviglia, ma il matrix è disabilitato, quindi vado ad agire come sopra.

**Comment by archeorosati** [comment]
come era la path da inserire per graphviz? non la ritrovo più nelle issues

**Comment by archeorosati** [comment]
trovata: /usr/local/Cellar/graphviz/2.40.1/bin

**Comment by slarosa** [comment]
@archeorosati quindi adesso installa i pacchetti python senza che tu debba intervenire tramite pip3?

per il matrix, conviene aprire un'altra issue (o riaprire quella di prima), questo si può chiudere allora?

**Comment by archeorosati** [comment]
Si può chiudere anche su altri pc mac che sto provando live qui al millepiani con varie versioni gira ;)

**Comment by archeorosati** [comment]
Si comunque installa i pacchetti python senza intervenire su pip3, ma non so se è a causa del fatto che sono già stati precedentemente salvati, però devo dire che su un Mac Sierra 10.13 qui all'open day abbiamo installato due ore fa usando pip3.
