### ISSUE TITLE
Scheda US - Esportazione tavole: errato adattamento del foglio.

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#14]
Scheda US - Esportazione tavole. Se si prova ad esportare il DB di test "Sito Archeologico" alcune US sono tagliate nei bordi: vedere US 1 e US2 (Forse la 2 non è inclusa nel db di prova).

**Comment by enzococca** [comment]
Sembra strano a me le us sono stampaye tutte al centro a scala 1:20

Il Lun 7 Mag 2018, 21:03 Luca Mandolesi <notifications@github.com> ha
scritto:

**Comment by pyarchinit** [comment]
![tavola_13_us_1](https://user-images.githubusercontent.com/1929829/39722431-0a79107e-5243-11e8-9da8-adef0e157c99.png)
