### ISSUE TITLE
PROBLEMA INSTALLAZIONE PYARCHINIT UBUNTU 14.04

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#167]
Ho provato a installare PyArchinit su Ubuntu 18.04
![Screenshot from 2019-03-13 18-43-48](https://user-images.githubusercontent.com/10104718/54309602-62826800-45c8-11e9-8a64-0c7d1223b29e.png)
Ho installato tutte le dipendenze richieste in questo messaggio. Nonostante questo il plugin non si installa e mi da questo errore
![Screenshot from 2019-03-13 19-34-04](https://user-images.githubusercontent.com/10104718/54309703-98bfe780-45c8-11e9-818f-30af87903eae.png)

**Comment by enzococca** [comment]
Avvia qgis come admin. Da terminale scrivi: sudo qgis

Il Mer 13 Mar 2019, 20:46 montarob <notifications@github.com> ha scritto:

**Comment by enzococca** [comment]
hai risolto? sei si chiudi la iusse

**Comment by kephir** [comment]
Buongiorno, ho avuto un problema simile dopo aver installato, su Ubuntu 18.04, l'ultima versione di Qgis (3.10.1-A Coruña) e successivamente l'ultima di PyArchinit. A differenza di @montarob ho però due pacchetti mancanti in più.
Ho dato l'ok, pensando e sperando che installasse automaticamente i pacchetti citati, ma niente. 
Avvio Qgis ogni volta da terminale tramite il comando sudo qgis ma niente è cambiato.
Come posso risolvere?
![Schermata da 2019-12-13 15-13-39](https://user-images.githubusercontent.com/58853289/70806680-2630a200-1dbc-11ea-8ac1-743fcbce026f.png)
![Schermata da 2019-12-13 15-22-23](https://user-images.githubusercontent.com/58853289/70806838-7c9de080-1dbc-11ea-9dde-4df7ca57c857.png)

**Comment by enzococca** [comment]
Ciao,
Puoi installarli manualmente oppure prova da terminale ad avviare
scrivendo  sudo su e poi qgis.
Fa sapere
Ciao
Enzo

Il Ven 13 Dic 2019, 15:23 kephir <notifications@github.com> ha scritto:
