### ISSUE TITLE
US Sheet - Problem with matrix exportation

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#168]
Some number are replicated.
Check the code in pyarchinit matrix code.

![immagine](https://user-images.githubusercontent.com/1929829/54419241-40dbca80-4707-11e9-812d-5ae9041ab20b.png)

**Comment by antoniodambrosio** [comment]
come si risolve questo problema ? grazie infinite

**Comment by enzococca** [comment]
Ho fatto un aggiornamento provalo e fa sapere

Il Sab 16 Mar 2019, 15:51 antoniodambrosio <notifications@github.com> ha
scritto:

**Comment by enzococca** [comment]
Fix it!!! provatelo a me funziona bene ora!
