### ISSUE TITLE
Scheda Documentazione

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#17]
Quando si apre la scheda il campo nome documentazione riceve il valore:

<built-in method ...ecc ecc.

**Comment by slarosa** [comment]
@pyarchinit  Il campo che valore ha nel DB?

**Comment by pyarchinit** [comment]
Ha salvato il valore: <built-in method text of QLineEdit object at 0x0E89D8E8>

**Comment by pyarchinit** [comment]
Confermo era solo un vecchio record malandato.
