### ISSUE TITLE
Scheda US/USM Bug in Empty fields 

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#174]
Scheda US/USM Bug in Empty fields 

In USM or Measure tab some fields are not emptied properly when new search is clicked

![immagine](https://user-images.githubusercontent.com/1929829/54611541-6f370e00-4a57-11e9-9be9-d9504475890a.png)

![immagine](https://user-images.githubusercontent.com/1929829/54611746-d654c280-4a57-11e9-9a20-c0ae84bddf29.png)

**Comment by enzococca** [comment]
Spiega meglio il problema. Quali campi non vengono riempiti come si attende?

Il Mar 19 Mar 2019, 14:59 Luca Mandolesi <notifications@github.com> ha
scritto:

**Comment by pyarchinit** [comment]
Funziona. Chiudo.
