### ISSUE TITLE
Problem on DB Postgres for varchar length

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#178]
For english version: the database postgres has some restrinctions in varchar field type, depending from italian language.
Examplese:

retrieved is varchar(2) because it depends on the Italian: it is Si / NO.
But in english become Yes / No and return error

![immagine](https://user-images.githubusercontent.com/1929829/54918886-a85ffa00-4eff-11e9-90dd-829a61b91c6a.png)

**Comment by enzococca** [comment]
Questo succede se hai un vecchio db lo devi risolvere manualmente.

Il Lun 25 Mar 2019, 13:15 Luca Mandolesi <notifications@github.com> ha
scritto:

**Comment by pyarchinit** [comment]
Chiudo
