### ISSUE TITLE
Avvio scheda Image Viewer: Errore di esecuzione

### ISSUE THREAD

**Issue by Heryx** [pyarchinit/pyarchinit#180]
Ciao ragazzi, 
quando avvio la scheda per la gestione delle immagini mi spunta questo errore:

`(sqlite3.OperationalError) no such column: media_thumb_table.path_resize [SQL: 'SELECT media_thumb_table.id_media_thumb AS media_thumb_table_id_media_thumb, media_thumb_table.id_media AS media_thumb_table_id_media, media_thumb_table.mediatype AS media_thumb_table_mediatype, media_thumb_table.media_filename AS media_thumb_table_media_filename, media_thumb_table.media_thumb_filename AS media_thumb_table_media_thumb_filename, media_thumb_table.filetype AS media_thumb_table_filetype, media_thumb_table.filepath AS media_thumb_table_filepath, media_thumb_table.path_resize AS media_thumb_table_path_resize \nFROM media_thumb_table'] (Background on this error at: http://sqlalche.me/e/e3q8)`

**Comment by enzococca** [comment]
hai risolto? se si chiudi la iusse per favore 
E
