### ISSUE TITLE
Errore in installazione Mac OS Sierra 10.12.6

### ISSUE THREAD

**Issue by archeorosati** [pyarchinit/pyarchinit#191]
Buonasera ragazzi,
andando a reinstallare il mio pyarchinit accade un errore che vi trascrivo:

sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused Is the server running on host "37.139.2.71" and accepting TCP/IP connections on port 5432? (Background on this error at: http://sqlalche.me/e/e3q8) 

allego anche un'immagine
![Schermata 2019-06-04 alle 17 00 39](https://user-images.githubusercontent.com/39003545/58890135-58b16200-86ea-11e9-9047-3e901279ad77.png)
![Schermata 2019-06-04 alle 17 00 49](https://user-images.githubusercontent.com/39003545/58890140-5b13bc00-86ea-11e9-9907-bd9e3c351d35.png)

**Comment by enzococca** [comment]
Quella è la connessione al sftp per lizmap ma se non lo usi non ti dovrebbe
dare questo errore

Il Mar 4 Giu 2019, 18:01 archeorosati <notifications@github.com> ha scritto:

**Comment by archeorosati** [comment]
Da quando l'ho messa poi ha fatto un crash pyarchinit si è tolto con ogni tool e non riesco più a reintrodurlo. Secondo te dove sta l'indirizzo per poterlo eliminare e ristabilire l'installazione?

**Comment by enzococca** [comment]
Se ti crasha qgis non è per questo. Hai settato male qualcosa nelle
variabili d'ambiente di qgis. Questa funzione è vecchia. L'ho messa prima
che facevate archeobot. Cmq se vuoi provare vai in
pyarchinit-master/gui/pyarchinitconfig.py e commenta import pysftp e tutta
la funzione def on_tryconnection_pressed(self)...
Fino alla fine. Praticamente è l'ultima funzione




Il Mer 5 Giu 2019, 18:20 archeorosati <notifications@github.com> ha scritto:

**Comment by archeorosati** [comment]
Ok ho commentato la funzione import pystp e tutta l'ultima funzione ora ho questo messaggio ![Schermata 2019-06-06 alle 09 56 04](https://user-images.githubusercontent.com/39003545/59017199-45fe7080-8843-11e9-8cf5-abc64221e615.png)

**Comment by archeorosati** [comment]
**[Risolto]** 
Ho eliminato interamente la cartella e ho installato di nuovo Pyarchinit da Zip, grazie del supporto. Come sempre preziosissimo Enzo

**Comment by enzococca** [comment]
Eh stavi utilizzando la mia versione che hai scricato dal mio github.

Il Gio 6 Giu 2019, 11:21 archeorosati <notifications@github.com> ha scritto:
