### ISSUE TITLE
errore nel caricamento del plugin

### ISSUE THREAD

**Issue by lucafornari** [pyarchinit/pyarchinit#193]
![image](https://user-images.githubusercontent.com/26907221/60266885-44c3df00-98e9-11e9-96cb-d892160cdb73.png)

Impossibile caricare il plugin 'pyarchinit-0.3.7' 

ModuleNotFoundError: No module named 'pyarchinit-0' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python\qgis\utils.py", line 309, in loadPlugin
    __import__(packageName)
  File "C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python\qgis\utils.py", line 686, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'pyarchinit-0'

Nella reinstallazione del plugin mi ha dato questo errore. Sottolineo che ho già rinominato la cartella pyarchinit...

**Comment by enzococca** [comment]
Non devi rinominare la cartella. Disinstalla e installa di nuovo.

Il Gio 27 Giu 2019, 15:40 lucafornari <notifications@github.com> ha scritto:

**Comment by lucafornari** [comment]
![image](https://user-images.githubusercontent.com/26907221/60432907-b9f22580-9c03-11e9-9f0d-387e9bdb058d.png)
Ho disinstallato e reinstallato ripetutamente ma l'errore continua a comparire....

**Comment by enzococca** [comment]
Questo errore te lo da perchè hai due versioni di pyarchinit. Controlla bene

Il Lun 1 Lug 2019, 14:26 lucafornari <notifications@github.com> ha scritto:

**Comment by lucafornari** [comment]
Ho riprovato disinstallando sia qgis che il plugin ma mi dà sempre quell'errore.
Io di pyarchinit vedo una sola versione.

**Comment by enzococca** [comment]
Mi mandi uno screenshot della cartella dove sononinstallati i plugin?

Il Lun 1 Lug 2019, 15:40 lucafornari <notifications@github.com> ha scritto:

**Comment by lucafornari** [comment]
![image](https://user-images.githubusercontent.com/26907221/60439342-fb3e0180-9c12-11e9-8663-09ec657e19ec.png)

**Comment by enzococca** [comment]
La tua cartella si chiama ptarchinit 0.3.8
Si dovrebbe chiamare pyarchinit-master.
Quindi credo che tu non abbia scaricato l ultima versione. Scaricala poi
disinstalli questa e da zip installi la versione scaricata.

Spero che ti risolva il problema

Il Lun 1 Lug 2019, 16:15 lucafornari <notifications@github.com> ha scritto:

**Comment by lucafornari** [comment]
Perdonami ma la versione master dove la posso trovare??

**Comment by lucafornari** [comment]
Scusa. Trovata

**Comment by enzococca** [comment]
Se ti funziona perfavore chiudi la iusse

Il Lun 1 Lug 2019, 17:48 lucafornari <notifications@github.com> ha scritto:

**Comment by lucafornari** [comment]
Sì, scusa. Alla fine ieri sera ho risolto. Ora chiudo la iusse.
