### ISSUE TITLE
Problema installando plugin Qgis Zanzibar su Fedora 30

### ISSUE THREAD

**Issue by Dagordraug** [pyarchinit/pyarchinit#194]
Salve!
sto provando il plugin su Fedora con Qgis Zanzibar, e non riesco a farlo partire.
Ho installato tutti i pacchetti dal gestore, ho scaricato il pacchetto di pyarchinit e, quando provo a installarlo dentro qgis come prima cosa mi dice che mancano alcuni pacchetti, e che provvederà a installarli. Una volta che ha fatto mi restituisce questo:

"INFO: It seems that R is not installed on your system or you don't have set the path in Pyarchinit config. Anyway the pyper module will be installed on your system, but you can not use archaezoology function"

E poi, alla fine, mi restituisce questo errore (che non mi ci stava in una singola schermata, per cui ve l'ho copiato)

**Impossibile caricare il plugin 'pyarchinit-master' a causa di un errore chiamando il metodo classFactory()** 

ModuleNotFoundError: No module named 'pyper' 
Traceback (most recent call last):
  File "/usr/lib64/python3.7/site-packages/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/__init__.py", line 152, in classFactory
    from .pyarchinitPlugin import PyArchInitPlugin
  File "/usr/lib64/python3.7/site-packages/qgis/utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/pyarchinitPlugin.py", line 32, in 
    from .pyarchinitDockWidget import PyarchinitPluginDialog
  File "/usr/lib64/python3.7/site-packages/qgis/utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/pyarchinitDockWidget.py", line 30, in 
    from .tabs.Archeozoology import pyarchinit_Archeozoology
  File "/usr/lib64/python3.7/site-packages/qgis/utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/tabs/Archeozoology.py", line 39, in 
    from pyper import R
  File "/usr/lib64/python3.7/site-packages/qgis/utils.py", line 737, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'pyper'

Versione Python: 3.7.3 (default, May 11 2019, 00:38:04) [GCC 9.1.1 20190503 (Red Hat 9.1.1-1)] 
Versione di QGIS: 3.8.0-Zanzibar Zanzibar, exported 

Percorso Python:
/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/gui/ui
/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/resources
/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/gui/ui
/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/resources
/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/gui/ui
/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/resources
/usr/share/qgis/python
/root/.local/share/QGIS/QGIS3/profiles/default/python
/root/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib64/python37.zip
/usr/lib64/python3.7
/usr/lib64/python3.7/lib-dynload
/usr/lib64/python3.7/site-packages
/usr/lib/python3.7/site-packages
/root/.local/share/QGIS/QGIS3/profiles/default/python

Non è una questione urgentissima perché ho una copia su windows che funziona benissimo, però mi piacerebbe capire se sto sbagliando io o se sono capitato di fronte a un problema!
Potete aiutarmi? grazie in anticipo per questo meraviglioso lavoro

**Comment by enzococca** [comment]
Prova ad avviare qgis come admin da shell: sudo qgis

Il Sab 29 Giu 2019, 13:34 Dagordraug <notifications@github.com> ha scritto:

**Comment by enzococca** [comment]
Per quanto riguarda r quello non è un errore ma un avviso. R è una sezione
sperimentale per la statistica che lo sinutilizza nella scheda
archeozoologia.
Per far si che non ti esca quell avviso devi installare anche r-base dal
gestore pacchetti.

Spero di averti aiutato

Il Sab 29 Giu 2019, 14:05 Enzo Cocca <enzo.ccc@gmail.com> ha scritto:

**Comment by Dagordraug** [comment]
Ok per R! però continua a non installarlo (ero già admin :/ )

**Comment by enzococca** [comment]
Disinstalla e reinstalla

Il Sab 29 Giu 2019, 19:53 Dagordraug <notifications@github.com> ha scritto:

**Comment by Dagordraug** [comment]
il plugin o qgis? perché il plugin ho provato a reinstallarlo già due volte...stesso risultato

**Comment by enzococca** [comment]
Puoi controllare che non hai due versioni installate?

Il Sab 29 Giu 2019, 20:01 Dagordraug <notifications@github.com> ha scritto:

**Comment by Dagordraug** [comment]
Certo! ma no, non ho doppioni...

**Comment by Dagordraug** [comment]
Io boh, s'è risolto da solo...anche se manca ancora R per l'archeozoologia. Se volete sapere qualcosa ditemelo, altrimenti chiudo qui

**Comment by enzococca** [comment]
In genere si spiega l'errore specificando tutte le caratteristiche e poi se
si è risolto, come. Questo te lo dico in quanto può essere utile anche ad
altri. Cmq sono contento che hai risolto. Ti prego solo di chiidere la
iusse.

E

Il Mar 2 Lug 2019, 22:37 Dagordraug <notifications@github.com> ha scritto:

**Comment by Dagordraug** [comment]
Sì, sono contento anch'io, solo non so come...
