### ISSUE TITLE
errore salvataggio

### ISSUE THREAD

**Issue by lucafornari** [pyarchinit/pyarchinit#197]
![image](https://user-images.githubusercontent.com/26907221/63845045-950efa00-c989-11e9-806c-f803700a0c01.png)

Ciao. Quando cerco di salvare le modifiche alla scheda US mi dà questo errore.

**Comment by enzococca** [comment]
Quando hai l'errore : list out range, significa che ti sei dimenticato di
inserire dei dati. I campi obbligatori nella scehda us/usm sono sito, area,
numero di us o usm e quindi scegliere il tipo US o USM.

Hai riempito questi campi?

Ciao
E

Il Mer 28 Ago 2019, 17:48 lucafornari <notifications@github.com> ha scritto:

**Comment by lucafornari** [comment]
Sì, li avevo riempito, adesso è risolto.
Grazie e a presto...
