### ISSUE TITLE
Problems to install pyarchinit in Windows 10.  

### ISSUE THREAD

**Issue by rotrigo** [pyarchinit/pyarchinit#198]
Hi.
I tried to install the addon in Qgis 3.8 (64 bit). I have followed all the steps that you mention in the tutorial and I have done them successfully, but Qgis 3.8 does not show me the addon before installation.  

I try to instal whit comand line in python but nothing happend. 

I delete folders in C disk an re-install but nothing happend. 
I try to install python enviromenth  but nothing happend. 
I try to install in new Pc but nothing happend. 

I think this problem has to do with environment variables or program versions.}

Thanks for help. 

![varialbes de entorno](https://user-images.githubusercontent.com/41752438/65897807-864fa480-e386-11e9-9848-a41831ef608d.png)
![pc](https://user-images.githubusercontent.com/41752438/65897809-864fa480-e386-11e9-9e38-ff4607aded11.png)

**Comment by enzococca** [comment]
Hi Rodrigo,
Check if you have two pyarchinit's versions installed on your pc (your
user/ AppData/Roaming/QGIS/QGIS3/profiles/default/python/plugins.

Than check if you have a folder called pyarchinit in your user. And check
if there is an subfolder called pyarchinit_DB_folder. Check also if in this
subfolder you have the file config.cfg.

Let me know

Cheers
E

Il Lun 30 Set 2019, 19:31 Rodrigo Mendoza Sánchez <notifications@github.com>
ha scritto:

**Comment by rotrigo** [comment]
Hi Enzo. 

i dont have 2 versions of pyarchinit. 
![image](https://user-images.githubusercontent.com/41752438/65911858-a8a3eb00-e3a3-11e9-96bd-8784635c8099.png)
![image](https://user-images.githubusercontent.com/41752438/65911912-c2ddc900-e3a3-11e9-80e5-a24cd2c696c2.png)
 


The subfolder contain the .cfg archive. 

![image](https://user-images.githubusercontent.com/41752438/65911665-55319d00-e3a3-11e9-9b8b-3a2ab5a884e4.png)

**Comment by enzococca** [comment]
I see you have installed just pyarchinit as plugin right? Try install an
other plugin from qgis and let me know

Il Lun 30 Set 2019, 23:00 Rodrigo Mendoza Sánchez <notifications@github.com>
ha scritto:

**Comment by rotrigo** [comment]
I install SCP Pluging. Works Fine.  Pyarchinit dont appear. 

![imagen](https://user-images.githubusercontent.com/41752438/65978437-7604fb80-e452-11e9-8079-5f7cca941399.png)

![imagen](https://user-images.githubusercontent.com/41752438/65978510-9a60d800-e452-11e9-8c2c-7fd09b4b356b.png)

**Comment by enzococca** [comment]
Open please the file config.cfg and sendme a screenshot what  you have.

Thaks
E

Il Mar 1 Ott 2019, 18:52 Rodrigo Mendoza Sánchez <notifications@github.com>
ha scritto:

**Comment by rotrigo** [comment]
![imagen](https://user-images.githubusercontent.com/41752438/65980241-85d20f00-e455-11e9-96d0-dfa344f11c6d.png)


Thanks¡

**Comment by enzococca** [comment]
Ok show me the path of this file please

Il Mar 1 Ott 2019, 19:12 Rodrigo Mendoza Sánchez <notifications@github.com>
ha scritto:

**Comment by rotrigo** [comment]
C:\Users\Biblioteca D\pyarchinit\pyarchinit_DB_folder 

 and other path: 

C:\Users\Biblioteca D\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pyarchinit-master\resources\dbfiles

**Comment by enzococca** [comment]
I update the plugin try to dowload and install again

Il Mar 1 Ott 2019, 20:01 Rodrigo Mendoza Sánchez <notifications@github.com>
ha scritto:

**Comment by rotrigo** [comment]
Same results. I try to install in Ubuntu linux. 

Thanks

**Comment by enzococca** [comment]
Hi, just to understand. When you open qgis do you have same message from
pyarchinit? Can you show me?

I think that you didn't install the python packages necessary.
Wich qgis do you have installed standalone or osgew4?

Il Mer 2 Ott 2019, 00:54 Rodrigo Mendoza Sánchez <notifications@github.com>
ha scritto:

**Comment by rotrigo** [comment]
When I install the addon and open qgis to test if it works, the messages that appear in the yotube tutorial appear.
![1](https://user-images.githubusercontent.com/41752438/66048647-ad35e400-e508-11e9-9f13-9a2d0616dad9.png)
![2](https://user-images.githubusercontent.com/41752438/66048652-ae671100-e508-11e9-8a49-f737af158c40.png)


The add-in appears as installed in the Qgis add-ons section, but does not appear anywhere in qgis, as the video shows.
![3](https://user-images.githubusercontent.com/41752438/66048663-b32bc500-e508-11e9-96ba-7512c37141f4.png)


I follow exactly the steps that appear in the tutorial, I have also installed (Yotube tutorial https://www.youtube.com/watch?v=ZNCaM0NMsmQ) the packages with the script that comes within the Rar file (install_modules.py). Through osgew4 I also tried.

Qgis install it through standalone.

**Comment by enzococca** [comment]
I'm sure the proble is in your pc. If the plugin had some problem, it given
you an error. Can you show me the proprietes of qgis. You find it, when
open qgis in settings - options - systems.

Thanks

Il Mer 2 Ott 2019, 16:36 Rodrigo Mendoza Sánchez <notifications@github.com>
ha scritto:

**Comment by enzococca** [comment]
If you have solved please close the iusse.
thanks

**Comment by rotrigo** [comment]
Hi E. I have a new laptop without any software installed.

Install qgis 3.8 and then the addon.

Same mistake.

I attached a photo what you asked me the last time in the new latop.

Regards.
<img width="517" alt="system1" src="https://user-images.githubusercontent.com/41752438/67092398-7a852000-f185-11e9-81b3-6b851594e2b7.PNG">

<img width="428" alt="system 2" src="https://user-images.githubusercontent.com/41752438/67092411-81139780-f185-11e9-9d2a-48a942493479.PNG">

<img width="392" alt="system3" src="https://user-images.githubusercontent.com/41752438/67092418-84a71e80-f185-11e9-9909-ee990c94d49b.PNG">
