### ISSUE TITLE
Problema installazione release 0.3.2

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#20]
Installando lo zip della release 0.3.2 si ottiene il seguente messaggio: 

Impossibile caricare il plugin 'pyarchinit-0.3.2' 

ModuleNotFoundError: No module named 'pyarchinit-0' 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 311, in loadPlugin
    __import__(packageName)
  File "C:/PROGRA~1/QGIS3~1.0/apps/qgis/./python\qgis\utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'pyarchinit-0'

**Comment by slarosa** [comment]
Per il testing conviene usare la versione master, tutte le correzioni ad eventuali bug vanno a finire nella master.

La release è qualcosa che deve entrare nel processo di rilascio del plugin nel repo di QGIS.

**Comment by pyarchinit** [comment]
Ok. Nella doc inserisco la master.
