### ISSUE TITLE
Scheda US - richiesta di modifica (misure)

### ISSUE THREAD

**Issue by MicheleFait** [pyarchinit/pyarchinit#213]
Nella sezione "Misure" della scheda di US sono presenti i campi "Profondità minima" e "Profondità massima" e "Altezza minima" e "Altezza massima".
Per quanto riguarda la "Lunghezza" c'è solo quella massima, mentre invece per la "larghezza" c'è solo quella media.
Sarebbe il caso di rendere tutto uniforme e inserire minima e massima ANCHE per "Lunghezza" e "Larghezza".

**Comment by enzococca** [comment]
da discuterne. Credo che quella finestra vada riorganizzata. c'è confusione e ridondanza sulle voci e se riguardano le misure us o usm

**Comment by MicheleFait** [comment]
concordo
