### ISSUE TITLE
Esportazione PDF scheda US - Non esporta la sezione documentazione

### ISSUE THREAD

**Issue by MicheleFait** [pyarchinit/pyarchinit#214]
Nessun valore inseribile nella sezione "Documentazione" della schede di US viene esportato nel PDF.
Si potrebbe anche eliminare dal PDF l'obsoleta distinzione tra foto B/N e digitali.

**Comment by pyarchinit** [comment]
Al momento è stato elaborato il seguente sistema:

Nella lista a tendina della documentazione appaiono 4 valori precompilati:

ICCD-Piante
ICCD-Prospetti
ICCD-Sezioni
ICCD-Foto

![immagine](https://user-images.githubusercontent.com/1929829/69651107-dfc70d80-106f-11ea-9887-191a006584e3.png)

Avrete 3 alternative:

1. Non compilare nulla e non apparirà nulla nel PDF;

2. Potete aggiungere tramite Thesaurus nuovi valori che **NON COMPARIRANNO** nel PDF ICCD;

3. Compilare solo col primo valore scelto dalla tendina: questo farà scrivere nel campo del PDF ICCD la sigla "SI";

_Esempio di compilazione in scheda:_



![immagine](https://user-images.githubusercontent.com/1929829/69651485-6e3b8f00-1070-11ea-9c52-e7a6b40ca539.png)

_Come appariranno nel PDF:_

![immagine](https://user-images.githubusercontent.com/1929829/69651434-5c59ec00-1070-11ea-96e0-fd2ac3418cd8.png)

3. Compilare con il primo valore da tendina ed elencare le sigle di tavole (ICCD-Piante), piante, sezioni, prospetti, foto. Queste appariranno nel PDF ICCD nell'ordine in cui le avrete scritte nella cella.

_Esempio di compilazione in scheda:_

![immagine](https://user-images.githubusercontent.com/1929829/69651880-0a659600-1071-11ea-9535-23c781adc464.png)

_Come appariranno nel PDF:_

![immagine](https://user-images.githubusercontent.com/1929829/69651826-f752c600-1070-11ea-9a8d-aaf9d0f5d4c7.png)

**Comment by enzococca** [comment]
ok!
