### ISSUE TITLE
Esportazione PDF scheda US - campi non presenti in scheda pyArch ma in Scheda Ministeriale

### ISSUE THREAD

**Issue by MicheleFait** [pyarchinit/pyarchinit#215]
Nel PDF ci sono quattro campi che non possono essere compilati durante l'inserimento dati nella scheda US (non esiste proprio la maschera di inserimento) ma che sono presenti sulla scheda ministeriale (e quindi non possiamo ignorarli...):
- N. Catalogo generale
- N. catalogo internazionale
- Tabelle materiali / RA
- Dati quantitativi dei reperti

**Comment by pyarchinit** [comment]
Per i primi due campi ho verificato e sono già presenti N. Catalogo generale e Internazionale 

![immagine](https://user-images.githubusercontent.com/1929829/67674731-93f44c00-f97d-11e9-8572-873ec2661ff3.png)

**Comment by pyarchinit** [comment]
Per le Tabelle Materiali e i dati Quantitativi reperti è necessario pensarci un attimo.

Se li inserissimo qui come "MEMO" si rischia che nessuno poi compili le schede Materiali e di conseguenza non avremmo in PDF: schede, elenchi, etichette casse, ecc.

Inoltre scrivendo due volte i medesimi dati, nella scheda US e nella scheda Reperti, si rischia di avere dati non coincidenti.

Propongo due soluzioni:

- Inserire i due campi per i materiali con una dicitura esplicita come valore di default nel campo oppure nell'etichetta (Questo campo non sostituisce la compilazione della scheda Materiali)

- Far inserire dalla scheda Materiali i dati che vogliamo in automatico nel PDF senza aggiungere i campi.
