### ISSUE TITLE
Scheda di US - Aggiunta Alert "Vuoi Salvare" in Vai all'US

### ISSUE THREAD

**Issue by MicheleFait** [pyarchinit/pyarchinit#216]
Nella sezione "Periodizzazione - rapporti stratigrafici" se si utilizza il tasto "Vai all'US" per saltare da un US all'altra per verificare i rapporti stratigrafici reciproci si perdono tutti i dati inseriti precedentemente e non salvati. Non compare nemmeno un warning, quindi la cosa è abbastanza pericolosa.

**Comment by enzococca** [comment]
Qui è una questione di metodo. Devi salvare per non perdere i dati. Non
puoi fare altrimenti. Salvi i dati e non perdi nulla

Il Gio 10 Ott 2019, 17:00 MicheleFait <notifications@github.com> ha scritto:

**Comment by MicheleFait** [comment]
Sì certo, hai ragione. Però un utente alle prime armi potrebbe cascarci... Non si potrebbe aggiungere un micro avviso, tipo "Salva prima di cliccare"?

**Comment by MicheleFait** [comment]
Vero anche questo :-)

**Comment by enzococca** [comment]
aggiunto warning
