### ISSUE TITLE
installazione Pyarchinit Mac

### ISSUE THREAD

**Issue by Giaco1789** [pyarchinit/pyarchinit#217]
buongiorno,
sto ultimando l'installazione del plugin ma al momento di impostare il percorso di Graphviz e R non mi fa proseguire. I tre puntini non sono cliccabile. A qualcuno è successo questo problema? Ho scaricato entrambi i software
grazie mille
<img width="1280" alt="Schermata 2019-10-15 alle 12 54 35" src="https://user-images.githubusercontent.com/41733273/66825676-0828fb80-ef4b-11e9-9be4-2eb405808583.png">

**Comment by enzococca** [comment]
I software Graphviz e R devono essere installati

Il Mar 15 Ott 2019, 12:55 Giaco1789 <notifications@github.com> ha scritto:

**Comment by Giaco1789** [comment]
si gli ho anche installati ma nulla

**Comment by enzococca** [comment]
Aspetta tu usi il mac? Quando avvi qgis ti chiede di installare quei
software? Perchè se ricordo bene per linux e mac non vi è bisogno di
settare la path

Il Mar 15 Ott 2019, 14:04 Giaco1789 <notifications@github.com> ha scritto:

**Comment by Giaco1789** [comment]
si uso il mac. quando avvio Qgis da adm non mi esce di installare i software infatti. Io stavo seguendo le istruzioni per installarlo e mi sono bloccato a questo passaggio. 
Inoltre trovo scritto di premere sulla "spina" e impostare i DB settings e quello che succede è questo (allego foto
<img width="1280" alt="Schermata 2019-10-15 alle 14 17 30" src="https://user-images.githubusercontent.com/41733273/66830836-b4bcaa80-ef56-11e9-892f-6f38d0d40091.png">
<img width="1280" alt="Schermata 2019-10-15 alle 14 17 48" src="https://user-images.githubusercontent.com/41733273/66830837-b5554100-ef56-11e9-9862-f8256094931a.png">

)

**Comment by enzococca** [comment]
Per quanto riguarda r e graphiz tutto a posto. Poi di default sei connesso
al db di pyarchinit sqlite. Se vuoi usare quello ppatgres devi postgres e
poi da installa layers nella scheda setting installi il db postgres.
Spero di esserti stao di aiuto

Il Mar 15 Ott 2019, 14:19 Giaco1789 <notifications@github.com> ha scritto:

**Comment by Giaco1789** [comment]
non capisco solo il motivo di questi errori quando vado a provare il plugin
<img width="1280" alt="Schermata 2019-10-15 alle 17 52 19" src="https://user-images.githubusercontent.com/41733273/66848020-a1203c80-ef74-11e9-822f-77720e73d3cd.png">

**Comment by Giaco1789** [comment]
forse ce l'ho fatta. ti aggiorno. intanto grazie mille per il supporto

**Comment by enzococca** [comment]
stai provando a connetterti con postgres? se non hai postgres installato e
poi non hai installato il db come ti ho suggerito ti d questo errore

Il giorno mar 15 ott 2019 alle ore 17:53 Giaco1789 <notifications@github.com>
ha scritto:

**Comment by pyarchinit** [comment]
> 
> 
> forse ce l'ho fatta. ti aggiorno. intanto grazie mille per il supporto

Problema risolto? Chiudiamo la issue?

**Comment by Giaco1789** [comment]
Si sì grazie mille



Inviato da Libero Mail per iOS


lunedì 28 ottobre 2019, 12:11 +0100 da notifications@github.com  <notifications@github.com>:
