### ISSUE TITLE
Aggiunta sigle thesaurus su tabella unità stratigrafiche disegno

### ISSUE THREAD

**Issue by CriDeVita** [pyarchinit/pyarchinit#218]
Salve a tutti,
sarei interessato a crearmi delle sigle aggiuntive su tabelle per le quali non avete rilasciato ancora i codici dei campi di riferimento. In particolare volevo aggiornare le sigle di alcuni campi del layer "unità stratigrafiche disegno", ma anche ulteriori layer. Avete un elenco delle sigle aggiornato per tutti i layer del db?
Grazie!

E comunque sono felicissimo di quello che siete riusciti a fare! oltre ad avere uno strumento utilissimo per il lavoro, mi sto divertendo un mondo!

**Comment by enzococca** [comment]
ciao,
se ho capito bene tu vorresti cambiare le sigle sui layer vettoriali? 
se fosse così i codici del thesaurus valgono per le tabelle alfanumeriche del db e non per quelle vettoriali. 

E
