### ISSUE TITLE
problema salvataggio poligoni pyunitastratigrafiche

### ISSUE THREAD

**Issue by CriDeVita** [pyarchinit/pyarchinit#221]
Sto provando a importare un vecchio scavo creato su cad sul sistema pyarchinit. Lavorando sui poligoni delle unità stratigrafiche importate sul gis come poligoni, ho provato a copiare alcuni degli oggetti sul layer delle unità stratigrafiche, ma una volta incollate, le modifiche non si salvano. mi esce questo messaggio di errore:

Impossibile applicare le modifiche al vettore pyunitastratigrafiche

Errori: ERRORE: 2 geometrie non aggiunte.
  
  Errori della sorgente dati:
      Errore di SQLite: UNIQUE constraint failed: pyunitastratigrafiche.id
    SQL: INSERT INTO "pyunitastratigrafiche"("the_geom","id","area_s","scavo_s","us_s","stratigraph_index_us","tipo_us_s","rilievo_orginale","disegnatore","data","tipo_doc","nome_doc") VALUES (ST_Multi(GeomFromWKB(?, 3004)),?,?,?,?,?,?,?,?,?,?,?)

**Comment by enzococca** [comment]
Ciao!
Per fare quello che vuoi tu la struttura tabellare da copiare deve essere
uguale a quella di pyarchinit unitastratigrafiche

E

Il Mar 7 Gen 2020, 15:19 CriDeVita <notifications@github.com> ha scritto:

**Comment by CriDeVita** [comment]
Ok, perfetto. Grazie per la dritta!

**Comment by CriDeVita** [comment]
Ho esportato la tabella pyunitastratigrafiche, l'ho ripulita e ho incollato all'interno di essa i poligoni del layer importato dal cad. Ho poi provato a passarli sulla tabella collegata al db, ma mi dà lo stesso errore

**Comment by enzococca** [comment]
Perdonami ma non ho capito. Tu vuoi copiare le geometrie del cad sul
vettore pyunitastratigrafiche giusto?.

Se sì la tabella vettoriale che vuoi incollare deve essere come quella di
pyunitastratigrafiche.

Spero di esserti stato di aiuto

Il Mar 7 Gen 2020, 15:32 CriDeVita <notifications@github.com> ha scritto:

**Comment by CriDeVita** [comment]
Provo a spiegare meglio il problema partendo dall'inizio

Ho estrapolato dal file cad degli shape poligonali del rilievo di scavo. All'inizio, senza necessità di modificare la tabella del file che ho importato, ho potuto copiare una delle USM del rilievo (ingombro muro e caratterizzazione), compilando poi la tabella con le informazioni necessarie.
Ad una seconda sessione, ho fatto un test: sono andato sulla scheda sito e ho cliccato tra i tools il pulsante che permette di disegnare le uuss afferenti al sito. Dopo questa operazione non mi è stato più possibile copiare altri gruppi di poligoni nel layer pyunitastratigrafiche. Se però copio singolarmente un poligono il layer lo accetta e posso salvarlo. Diversamente non è possibile fare. Seguendo il tuo consiglio ho creato per i poligoni importati anche una tabella simile a quella di pyarchinit ma non ottengo un risultato diverso.
Ti ringrazio per il supporto.

**Comment by enzococca** [comment]
Il problema allora risiede nella chiave primaria. Una volta che incolli i
dati,tramite il foeld calculator reindicizza. Fammi sapere

Il Mer 8 Gen 2020, 15:22 CriDeVita <notifications@github.com> ha scritto:

**Comment by enzococca** [comment]
Se vuoi mandami in pvt il file che vuoi incollare e provo anche io

Il Mer 8 Gen 2020, 15:22 CriDeVita <notifications@github.com> ha scritto:

**Comment by CriDeVita** [comment]
Ho provato a modificare l'id attraverso il comando @row number ma non mi permette di salvare. Ora ti giro lo shp dei poligoni, grazie per la disponibilità
