### ISSUE TITLE
Per Debian sostituire 'ensurepip' con 'pip' nell'installatore delel dipendenze

### ISSUE THREAD

**Issue by Exekias87** [pyarchinit/pyarchinit#235]
Hello,
come segnalato su Google Groups, per debian va modificato l'installer alla riga 56, sostituendo 'ensurepip' con 'pip'
`subprocess.check_call([cmd, '-m', 'pip'], shell=False)`

**Comment by enzococca** [comment]
Non va sostituito. esurepip serve a installare pip nel caso esso non sia
installato.

Il sab 6 giu 2020, 18:33 Exekias87 <notifications@github.com> ha scritto:
