### ISSUE TITLE
NON SI VEDE LA PREVIEW DELLE FOTO NELLA SEZIONE MEDIA - INVENTARIO MATERIALI

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#236]
Buongiorno,
una volta eseguito il Tag dei reperti attraverso il gestore delle Immagini e impostato il path delle thumbnails nei "Parametri di connessione" del plugin, all'interno della sezione "Media" della scheda Inventario Materiali, nonostante abbia attivato la modalità "Media Preview" non mi fa vedere la Preview ma solo il record del tag. Tuttavia se clicco sopra il record mi si apre comunque l'immagine.

**Comment by enzococca** [comment]
fixed
