### ISSUE TITLE
PyArchInit3 installato [pare] con successo in QGIS 3.12 su MacOS Catalina 10.15.5

### ISSUE THREAD

**Issue by nnenci** [pyarchinit/pyarchinit#238]
Salve a tutti e grazie tante per il vostro lavoro e supporto.

Volevo sperimentare l’uso del plugin, io che uso un MacBook Pro 13" del 2014 con su Catalina 10.15.5. Consapevole che non fosse diretta agli utenti con installato MacOS Catalina, ho comunque cercato di mettere in pratica la vs. recente guida per l'installazione del plugin sul mio computer:
https://github.com/pyarchinit/pyarchinit/issues/231?fbclid=IwAR27AiQIh6XB5ASwc4s3SP8hrP0wFEHPMCC3hdeZzV3yxXQy6lMdP9NMqgU

Posto che non sono un informatico ma un semplice utente smanettone, ho proceduto per tentativi, che cerco di ricostruire e riassumere come segue:

Ho seguito scrupolosamente le operazioni elencate al link di cui sopra, con solo due difformità:
1) Prima di disinstallare QGIS, avevo già installate le dipendenze in occasione di un precedente tentativo -fallito- di installazione di pyarchinit. In quell’occasione, avevo eseguito l’installazione delle dipendenze usando lo script “modules_installer.py”

2) al punto 2.1 della vostra guida segnalate la presenza di una scheda "archiviazione" che nelle mie preferenze di sistema non riesco a trovare (forse dipende dal fatto che in Catalina le funzioni sono diverse da Mojave?) e quindi ho disinstallato QGIS 3.12 usando l'app "APP Cleaner & Uninstaller", che credo abbia eliminato efficacemente tutte le dipendenze di QGIS dal sistema

Dopo aver eseguito tutte le istruzioni della vs. guida, una volta eseguito quelle al punto 3.4, ho lanciato QGIS 3.12 e mi sono apparsi due avvisi che riporto qui:
![1](https://user-images.githubusercontent.com/66723053/84261259-ca9d6200-ab1b-11ea-86c7-62d38672ecdb.png)
![2](https://user-images.githubusercontent.com/66723053/84261279-cf621600-ab1b-11ea-98e1-a4cff55ad51c.png)

Al che, mi sono accorto che graphiz e R non erano installati. Ho quindi proceduto come segue:
1) ho installato Homebrew eseguendo nel terminale questo comando: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)" [incluse le virgolette]
2) durante l’installazione di Homebrew, il sistema operativo ha provveduto a installare automaticamente X11, e l’ho lasciato fare
3) una volta completata l’installazione di X11, ho installato graphiz eseguendo nel terminale questo comando: “brew install graphviz” [senza virgolette]
4) ho installato R eseguendo nel terminale questo comando: “brew install r” [senza virgolette]

Dopodiché:
1) ho aperto QGIS, cliccato sul pulsante “configurazione plugin” sulla barra degli strumenti di pyarchinit
2) ho cliccato sul tab “Graphviz” e ho inserito il path cliccando sul pulsante con tre punti (copiare e incollare il path non funziona) e inserito il percorso seguente: “/usr/local/Cellar/graphviz/2.44.0/bin” [senza virgolette]. Ho poi cliccato sul pulsante “salva”
3) ho cliccato sul tab “R” e ho inserito il path cliccando sul pulsante con tre punti (copiare e incollare il path non funziona) e inserito il percorso seguente: “/usr/local/Cellar/r/4.0.0_1/bin” [senza virgolette]. Ho poi cliccato sul pulsante “salva”

Ho chiuso e riaperto QGIS, che si è avviato senza messaggi né avvisi, e pyarchinit sembra funzionare senza problemi. Dico “sembra” perché non ho mai usato il plugin finora, e mi riservo di provarlo prima di dare una risposta definitiva sull’effettivo funzionamento di tutte le sue componenti. Mi riservo di postare novità in merito, nel caso ce ne siano.

Ringrazio ancora tutti per il supporto e gli sviluppatori per il loro apprezzabile lavoro.
Saluti.

**Comment by enzococca** [comment]
Bene!
Ti ringrazio per il supporto

Il mer 10 giu 2020, 13:11 nnenci <notifications@github.com> ha scritto:

**Comment by nnenci** [comment]
Di nulla. Grazie a voi per il supporto. Potrei rompervi le scatole di nuovo in futuro.
Saluti,
Nicola
