### ISSUE TITLE
QGIS3 Windows8 Python 3.6 Pulsante Export Matrix disabilitato

### ISSUE THREAD

**Issue by Sandra9989** [pyarchinit/pyarchinit#24]
Buona sera sono Sandra Ramirez, 
Ho appena installato Pyarchinit 3 Garibaldi su QGIS 3, è bellissimo complimenti per il lavorone!!
L''installazione tramite ZIP funziona benissimo però entrando all'interno della Scheda US mi sono accorta che il pulsante Export Matrix è disabilitato
Cosa mi consigliate di fare?
Grazie mille, ancora complimenti per il lavoro
Sandra

**Comment by Archeomary** [comment]
Pure a me su Mac OS High Sierra 10.13.4! Stesso identico errore.

**Comment by archeoross** [comment]
Idem su Windows 10!

**Comment by enzococca** [comment]
Affinchè il matrix si attivi bisogna aver installato il programma graphviz (
graphviz.org) e da pyarchinit aprite l'icona a forma di spinotto e andate
nella sezione graphviz. Lì date il percoso fino alla cartella "bin" di
graphviz. Riavviate e dovrebbe funzionare. Fate sapere per favore

Il Gio 10 Mag 2018, 17:01 archeoross <notifications@github.com> ha scritto:

**Comment by Archeomary** [comment]
No, ci avevo provato e ci ho riprovato ma non funziona. Risulta ancora disabilitato.

**Comment by Archeomary** [comment]
Lo abbiamo fatto con proprio con @archeorosati qualche ora fa ma non funziona...o meglio, a lui funziona su Mac OS Sierra, a me su OS High Sierra no.

**Comment by enzococca** [comment]
Prova a mattere il percorso /usr/local/bin

Il Gio 10 Mag 2018, 18:15 Archeomary <notifications@github.com> ha scritto:

**Comment by Archeomary** [comment]
Niente, non va neanche così. Appena ho un tempo smanetto un po' e vi aggiorno. Su Windows @archeoross è riuscita ma io su MAC no (provando ad installare anche direttamente dal sito di graphviz e provando sia Homebrew che l'altro).

**Comment by archeoross** [comment]
io sono riuscita seguendo il commento di @enzococca scaricando il programma e riavviando con Windows 10.

**Comment by pyarchinit** [comment]
Abbiamo apportato modifiche. Se funziona correttamente il settaggio della path chiudiamo l'issue.

E' necessario:

1 - disinstallare il pyarchinit che avete sulla vostra macchina
2 - riscaricare la master
3 - reinstallare da zip la master.

**Comment by archeorosati** [comment]
Perfetto, ora va a meraviglia anche il Matrix ;) @Archeomary

**Comment by Archeomary** [comment]
Grandissimi! Funziona perfettamente :) L'unico problema per me rimangono le iconcine che non si vedono (ma magari facciamo un'altra issue).

**Comment by pyarchinit** [comment]
Perfetto, apri
