### ISSUE TITLE
Aggiornamento database sqlite: richiesta dell'epsg obbligatoria?

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#244]
Accanto al pulsante di aggiornamento per sqlite nelle configurazioni è presente un pulsante dove si richeide l'EPSG.

E' un campo obbligatorio per aggiornare anche le tabelle alfanumeriche?
Oppure serve per aggiornare un DB trasformando tutto da un sistema all'altro?

Anche qui direi di trovare un modo per dare un messaggio più chiaro all'utente.

ANche un warning al click sul pulsante non sarebbe male per chiedergli se è sicuro dell'EPSG.

**Comment by enzococca** [comment]
l'update postgresql e sqlite sono funzioni servono riallineare i vecchi db ai 'nuovi'. 
quindi se ho un db non allineato con la nuova release utilizzo questa funzione e per quanto rigurada sqlite devo settare l'epsg con cui è stato creato il db vecchio
