### ISSUE TITLE
Paradosso per query Sito in config

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#247]
In configurazione, la lista a tendina dei siti, da cosa è derivata?
Se dai siti allora in messaggio in scheda US non è congruente perchè segnala che il sito non esiste.

**Comment by enzococca** [comment]
Se aprendo la scheda us esce il warning che il sito non esiste significa
che nella scheda sito non c'è tale sitoo ppure che non é stat creata ancora
nessuna us con questo sito Pertanto bisoga crearlo

Il mer 28 ott 2020, 13:55 Luca Mandolesi <notifications@github.com> ha
scritto:
