### ISSUE TITLE
ERRORE SCHEDA US: IndexError: list index out of range !!!!

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#266]
Ho cretao un nuovo db;
Ho creato un nuovo sito, e ho creato subito tre schede US dai tools della scheda di sito ma appena apro la scheda US e provo a compilare i campi o semplicemente fare un search mi compare questo errore:

Si è verificato un errore durante l'esecuzione del codice Python: 

IndexError: list index out of range 
Traceback (most recent call last):
  File "C:/Users/rober/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit\tabs\US_USM.py", line 4334, in on_pushButton_new_search_pressed
    if self.BROWSE_STATUS != "f" and self.check_record_state() == 1:
  File "C:/Users/rober/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit\tabs\US_USM.py", line 4124, in check_record_state
    elif self.records_equal_check() == 1 and ec == 0:
  File "C:/Users/rober/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit\tabs\US_USM.py", line 5612, in records_equal_check
    self.set_LIST_REC_CORR()
  File "C:/Users/rober/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit\tabs\US_USM.py", line 5608, in set_LIST_REC_CORR
    self.DATA_LIST_REC_CORR.append(eval("unicode(self.DATA_LIST[self.REC_CORR]." + i + ")"))
  File "", line 1, in 
IndexError: list index out of range

Versione Python: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
Versione di QGIS: 3.10.6-A Coruña A Coruña, ec80021f49 

Percorso Python:
C:\Users\rober\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pyarchinit\gui\ui
C:\Users\rober\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pyarchinit\resources
C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python
C:/Users/rober/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/rober/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.10/apps/qgis-ltr/./python/plugins
C:\OSGeo4W64\apps\Python37\Scripts
C:\Program Files\QGIS 3.10\bin\python37.zip
C:\PROGRA~1\QGIS3~1.10\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib
C:\Program Files\QGIS 3.10\bin
C:\Users\rober\AppData\Roaming\Python\Python37\site-packages
C:\PROGRA~1\QGIS3~1.10\apps\Python37
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.10\apps\Python37\lib\site-packages\Pythonwin
C:/Users/rober/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\rober\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\kmltools\libs
C:/Users/rober/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit

**Comment by montarob** [comment]
questa cosa potrebbe essere causata dal fatto che nella query iniziale sulla scelta del sito (parametri di connessione) era ancora settato sul sito dell'ultimo db usato.

**Comment by enzococca** [comment]
Leggere bene i messaggi, se il sito non esiste viene esplicitato nel warning al apertura della scheda
