### ISSUE TITLE
SCHEDA TOMBA: IMPOSSIBILE INSERIRE IL "N. DI INDIVIDUO"

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#273]
Dopo aver compilato la scheda Individuo, passo alla compilazione della scheda Tomba. Tuttavia non mi fa inserire il numero individuo: la tendina rimane bloccata senza possibilità di scelta.

**Comment by enzococca** [comment]
Devi prima salvare

Il dom 15 nov 2020, 19:58 montarob <notifications@github.com> ha scritto:

**Comment by montarob** [comment]
Ho prima salvato ma poi non mi fa comunque immettere gli individui

**Comment by enzococca** [comment]
devi aver creato la struttura e nella scheda individuo devi aver messo la struttura poi riempi la scheda tomba

**Comment by enzococca** [comment]
cmq aggiorna all'ultima versione (2.0.5) e controlla
