### ISSUE TITLE
Scheda US - Richiesta salvataggio modifica record dopo creazione in automatico

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#283]
Dopo aver creato un nuovo sito "test", ho creato dal sistema di generazione in automatico delle schede US 10 record, dall'1 al 10.
Dopo aver cercato in scheda US (senza aver bloccato il sistema su un sito solo) i Sito test appena creato e aver cliccato su "freccia avanti di 1 step", il sistema ha chiesto se volevo salvare le modifiche nonostante non sia stato modificato il valore di nessun campo.

**Comment by enzococca** [comment]
nelle funzioni di avanzamento schede c'è una istruzione che compara il record temporaneo con il record corrente. questo provoca quando si creano le schede una sorta di disparità e quindi la stampa del messaggio. Bisognerebbe mettere una specie di refresh

**Comment by enzococca** [comment]
fixed in pyarchinit3
