### ISSUE TITLE
toolbar con i tasti privi di icone

### ISSUE THREAD

**Issue by lucafornari** [pyarchinit/pyarchinit#29]
Salve a tutti,
mi capita questo: dopo aver installato pyarchinit ho aperto la scheda di sito, ma vedo che succede anche con le altre schede, e a video non compaiono le icone che distinguono i singoli tasti; si riesce a capire di cosa si tratta solo portandoci su il cursore, facendo così comparire lafinestra di suggerimento.
E' capitato a qualcuno? Avete risolto?
Grazie

Luca

**Comment by enzococca** [comment]
Che sistema operativo usi?

Il Lun 16 Lug 2018, 21:40 lucafornari <notifications@github.com> ha scritto:

**Comment by lucafornari** [comment]
Windows 10

**Comment by enzococca** [comment]
Se vai nella cartella plugin di qgis3 assicurati che non hai due versioni
di pyarchinit installate. E se ne hai una cime si chiama la cartella?

Il Mer 25 Lug 2018, 07:55 lucafornari <notifications@github.com> ha scritto:

**Comment by lucafornari** [comment]
Ho installato  una sola versione del programma, ma francamente nella cartella QGIS 3.2\apps\qgis\plugins ho una serie di file .dll, ma non vedo un file pyarchinit.

**Comment by lucafornari** [comment]
Ok. Ho controllato ma nel percorso indicato ho solo una versione di pyarchinit.
Grazie.

**Comment by enzococca** [comment]
Hai installato la versione master?

Il Gio 26 Lug 2018, 21:22 lucafornari <notifications@github.com> ha scritto:

**Comment by lucafornari** [comment]
Sì
