### ISSUE TITLE
IMPOSSIBILE INSERIRE APOSTROFO NEL CAMPO NOME DOCUMENTAZIONE DELLA SCHEDA DOCUMENTAZIONE

### ISSUE THREAD

**Issue by chiara-difronzo** [pyarchinit/pyarchinit#292]
Nel campo nome documentazione della scheda documentazione è impossibile inserire APOSTROFO.

**Comment by enzococca** [comment]
Non mi risulta. Stai lavorando con l'ultima versione rilasciata? (v2.0.6)

**Comment by enzococca** [comment]
Comunque nel campo nome documentazione ti suggerisco di mettere il numero. Invece nel campo tipo documentazione andrebbe messa la sigla Iccd-Piante o Iccd-Sezioni o Iccd-Prospetti
