### ISSUE TITLE
PERIODIZZAZIONE: NON SI CREA LA VIEW

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#293]
Dopo aver compilato le schede di periodizzazione con i vari periodi e fasi, cliccando sul GIS viewer non si vede nulla; o meglio carica il layer della view ma la view risulta vuota.

**Comment by enzococca** [comment]
per visualizzare dal gis viewer ln scheda periodizzazione, effettua una ricerca e poi schiaccia il pulsante gis viewer. Attenzione devi aver creato il codice periodo nella scheda us

**Comment by montarob** [comment]
IL PROBLEMA ERA LEGATO AL CODICE DI PERIODO, VEDI ISSUE 294.
