### ISSUE TITLE
IMPOSSIBILE CREARE CODICE DI PERIODO

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#294]
Fatta tutta la periodizzazione sia nella scheda di periodizzazione che nella sezione "rapporti stratigrafici" della scheda US, cliccando su "Crea codice periodo" Qgis crascia!!

**Comment by enzococca** [comment]
é probabile che ci sia qualcosa che non va nel tuo db o cmq che hai inserito male i dati. ricontrollali

**Comment by montarob** [comment]
Qgis crasciava perchè erano scritti male i periodi e le fasi. Qgis quindi faceva i conti in negativo. 
LA REGOLA E': IL PERIODO PIU ANTICO DEVE AVERE IL CODICE PERIODO 1.
QUINDI IL CODICE PERIODO VA DAL N. 1 DEL PIU ANTICO A N DEL PIU RECENTE.
