### ISSUE TITLE
scheda tomba: il valore nr individuo non viene mantenuto  quando si fa una ricerca e si cancella

### ISSUE THREAD

**Issue by enzococca** [pyarchinit/pyarchinit#297]
CON IL BRENCH 2.1.0 NON CRASCIA PIU E ANCHE LA VIEW FUNZIONA BENE.
TUTTAVIA SORGE UN ALTRO MALFUNZIONAMENTO:
NEL MOMENTO IN CUI FAI CERCA E TROVA NON MANTIENE PIù IL N. INDIVIDUO. NEL MIO CASO SPECIFICO HO FATTO UN TEST CON SOLO DUE RECORD E QUANDO FACCIO CERCA E TROVA NON MANTIENE PIù NELLA RICERCA IL N. INDIVIDUO 1 (VEDI SOTTO):

PRIMA DI CERCA E TROVA:
![scheda_TOMBA2](https://user-images.githubusercontent.com/10104718/99901613-0be39180-2cb8-11eb-83cb-eb4f2aa6a08c.JPG)

DOPO LA RICERCA:
![scheda_TOMBA3](https://user-images.githubusercontent.com/10104718/99901627-1dc53480-2cb8-11eb-81d8-a7166468dd14.JPG)

OVVIAMENTE NON SI MANTIENE NEMMENO NELLA VIEW:
![view_individuo](https://user-images.githubusercontent.com/10104718/99901632-35042200-2cb8-11eb-9bf5-2fc93db353bb.JPG)

_Originally posted by @montarob in https://github.com/pyarchinit/pyarchinit/issues/296#issuecomment-731728602_

**Comment by montarob** [comment]
PROBLEMA RISOLTO NELLA VERSIONE 2.1.2
