### ISSUE TITLE
Scheda US "list index out of range"

### ISSUE THREAD

**Issue by Heryx** [pyarchinit/pyarchinit#30]
Ciao ragazzi, apro la scheda US e mi da questo messaggio di errore. Inoltre non spunta l'icona del tasto us.

**Comment by Heryx** [comment]
Versione di GIS 3.2.1

**Comment by pyarchinit** [comment]
Per caso hai eliminato tutti i record dal DB?

**Comment by Heryx** [comment]
Si in questa versione di Qgis ho il db vuoto. Quindi è questo il problema?
