### ISSUE TITLE
IMPOSSIBILE CARICARE TABELLE DA UN DB AD UN ALTRO TRAMITE TOOL DI IMPORTAZIONE

### ISSUE THREAD

**Issue by antoniomanna** [pyarchinit/pyarchinit#306]
Ho scaricato la nuova versione di PyArchinit 2.1.7, ho creato un nuovo db e spoi sto cercando di importare vecchie tables da un vecchio db ad uno nuovo ma mi da questo errore:

sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: site_table [SQL: SELECT site_table.id_sito AS site_table_id_sito, site_table.sito AS site_table_sito, site_table.nazione AS site_table_nazione, site_table.regione AS site_table_regione, site_table.comune AS site_table_comune, site_table.descrizione AS site_table_descrizione, site_table.provincia AS site_table_provincia, site_table.definizione_sito AS site_table_definizione_sito, site_table.sito_path AS site_table_sito_path, site_table.find_check AS site_table_find_check FROM site_table] (Background on this error at: http://sqlalche.me/e/13/e3q8)

**Comment by enzococca** [comment]
Ciao,
Se stai importando dati da un vecchio db in uno nuovo devi prima
aggiornarlo se no i db non sono allineati.

Quindi connettiti al db che vuoi importare lo aggiorni con il tool update
sqlite inserendo anche l epsg con cui hai creato il database dopo puoi
trasferire i dati

Il mar 24 nov 2020, 10:51 antoniomanna <notifications@github.com> ha
scritto:

**Comment by enzococca** [comment]
i db devono essere nell cartella pyarchinit_DB_manager
