### ISSUE TITLE
SCHEDA TOMBA: NON SALVA SUBITO IL N. INDIVIDUO

### ISSUE THREAD

**Issue by chiara-difronzo** [pyarchinit/pyarchinit#311]
Quando si crea una scheda tomba il numero di individuo non sempre viene salvato al primo tentativo.

**Comment by enzococca** [comment]
Problema noto, verrà corretto nella prossima release

Il lun 7 dic 2020, 13:28 chiara-difronzo <notifications@github.com> ha
scritto:
