### ISSUE TITLE
RAPPORTO DI UGUALIANZA NELL'ESPORTAZIONE DEL MATRIX

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#313]
IL RAPPORTO DI UGUALIANZA ESPRESSO DAL MATRIX DOVREBBE ESSERE RAPPRESENTATO CON I DUE QUADRATI DEI DUE NUMERI DI US UGUALI SULLO STESSO PIANO E NON UNO SOPRA L'ALTRO:
in questo esempio le UUSS 38 e 54 sono una uguale all'altra, eppure esse vengono rappresentate con 54 sopra 38.
![elimina](https://user-images.githubusercontent.com/10104718/102718333-e615d080-42e7-11eb-89fa-d449c61fc551.jpeg)

**Comment by enzococca** [comment]
Dovrebbe ma non é mai stato cosí.
Problema aperto per ora

Il dom 20 dic 2020, 17:22 montarob <notifications@github.com> ha scritto:
