### ISSUE TITLE
ESPORTAZIONE MATRIX v. 2.3.0 NON CORRETTA

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#320]
L'esportazione del matrix con la spunta attiva per le voci "leganda" e "Periodizzazione"con la nuova versione 2.3.0 non è corretta, nel senso che esporta un matrix dove si leggono solamente le periodizzazioni ma non sono riportati i numeri delle UUSS.
vedi esempio seguente:
![Harris_matrix_28_12_2020_17_9_38_tred dot](https://user-images.githubusercontent.com/10104718/103227953-f81ef100-492f-11eb-831a-d5c55040af93.jpg)
 Se invece si esporta senza quelle spunte allor lo costruisce correttamente:
![Harris_matrix_28_12_2020_17_9_14_tred dot](https://user-images.githubusercontent.com/10104718/103227984-0bca5780-4930-11eb-8306-315df7026bee.jpg)

**Comment by enzococca** [comment]
Prova due volte

Il lun 28 dic 2020, 17:14 montarob <notifications@github.com> ha scritto:

**Comment by montarob** [comment]
Ho provato ma è lo stesso...ho esportato vari volte...(vedi esempio sotto)
![Harris_matrix_28_12_2020_17_48_19_tred dot](https://user-images.githubusercontent.com/10104718/103230158-015e8c80-4935-11eb-9d28-8c04cb289017.jpg)
