### ISSUE TITLE
Problemi con prof e pyarchinit

### ISSUE THREAD

**Issue by Berserkr11** [pyarchinit/pyarchinit#325]
Buongiorno @enzococca Io aprendo QGIS 3.16.3 riscontro questi problemi. Come sistema operativo io utilizzo un MacBook Pro High Sierra 10.13.6
<img width="1114" alt="Schermata 2021-01-30 alle 12 24 09" src="https://user-images.githubusercontent.com/78225878/106355159-90751080-62f6-11eb-88d8-37fcf29f63c2.png">
<img width="427" alt="Schermata 2021-01-30 alle 12 24 36" src="https://user-images.githubusercontent.com/78225878/106355161-93700100-62f6-11eb-8e4e-719d8ec00ce5.png">
<img width="426" alt="Schermata 2021-01-30 alle 12 24 45" src="https://user-images.githubusercontent.com/78225878/106355162-94089780-62f6-11eb-98d2-997633082353.png">
<img width="1113" alt="Schermata 2021-01-30 alle 12 24 55" src="https://user-images.githubusercontent.com/78225878/106355163-94089780-62f6-11eb-9346-11e841a349c5.png">

**Comment by enzococca** [comment]
Ciao,
per quanto riguarda il pluin qprof non posso aiutarti devi aprire una iusse sul loro github.
invece, per pyarchinit le prime due immagini che mostri non sono un errore ma un warning ovvero R software (che al momento è solo in fase sperimentale ma non utilizzabile) e Graphviz che ti serve per creare i matrix. Una volta che li hai installati devi settare da pyarchinit la path dalla finestra configurazione pyarchinit nelle apposite sezioni graphviz e R. Pyarchinit comunque ti funziona uguale anche se non li hai installati. L'errore che posti potrebbe essere dovuto ad un db vecchio che hai. prova a rinominare il db nella cartella  pyarchinit/pyarchinit_DB_folder e riavvia qgis. Poi fammi sapere. Ciao E
