### ISSUE TITLE
Scheda US: altre caratteristiche USM: modificare il layout.

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#350]
Scheda US: altre caratteristiche USM: modificare il layout.

**Comment by enzococca** [comment]
non capisco il motivo. mi sembra che sono visibili tutti i campi e si differenziano tra loro. spiegare bene altrimenti chiudere la iusse

**Comment by pyarchinit** [comment]
Forse manca qualche ruler? Spariscono i pulsanti.
![immagine](https://user-images.githubusercontent.com/1929829/108044782-ff669f00-7042-11eb-86a7-c64c869bc7f0.png)
