### ISSUE TITLE
Debug scheda di sito – 30/01/2021 Sqlite

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#357]
Debug scheda di sito – 30/01/2021 Sqlite

1- Prima ancora di aver fatto qualsiasi cosa, cliccando sul tasto “Siti” (connesso a sqlite e senza query di siti attivata).

![immagine](https://user-images.githubusercontent.com/1929829/106478201-41231180-64a9-11eb-87ab-0de1ea93b80a.png)

Cliccando su ok compare la solita finestra “non hai settato alcun sito, vuoi settarne uno?” Premendo annulla carica regolarmente i siti.

**Comment by enzococca** [comment]
aggiornare db
