### ISSUE TITLE
Scheda Sito - Sezione dati descrittivi

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#358]
2- Sezione dati descrittivi
- Nel campo “provincia” ci sono, oltre alle provincie, anche Basilicata, Calabria, Campania e Emilia-Romagna
- Forlì Cesena è scritto “Forl'-Cesena”, senza la “i”.
- Si potrebbe implementare con dei dati precompilati il campo “Definizione” del sito (un po' già ce ne sono).

**Comment by enzococca** [comment]
Il campo definizione va compilato tramite thesaurus
