### ISSUE TITLE
Scheda Sito - Carica layer

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#359]
3- Sezione tools
- Generazione automatica delle schede: provata la prima volta, con messaggio “US generate con successo”. le US non erano presenti tra le schede (il numero di record totali delle schede era rimasto immutato). Riprovato facendo le stesse cose, le schede si sono generate.
- Pulsante “Carica layer per il disegno”: manda questo alert
![immagine](https://user-images.githubusercontent.com/1929829/106478448-80e9f900-64a9-11eb-8f74-9b6925855619.png)

Poi alert con “negative doc”, “tafonomia”. Alla fine carica i layer come nell'immagine sotto
![immagine](https://user-images.githubusercontent.com/1929829/106478506-8f381500-64a9-11eb-9aee-803db12d6533.png)

- Pulsante “Carica layer per questo sito”: manda questo alert (oltretutto con refuso reSgistro)

![immagine](https://user-images.githubusercontent.com/1929829/106478605-a70f9900-64a9-11eb-9859-4f3cebf6ceb5.png)

Poi altro alert su “Tomba” e infine un generico alert “Layer not valid!”, mostrato due volte senza altre specificazioni. Alla fine carica comunque i layer.

**Comment by enzococca** [comment]
aggiornare il db
