### ISSUE TITLE
6 - Bug sul sistema di multiutenza con postgreSQL - Aperto

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#36]
Sistemazione del bug per lavorare in multiutenza su postgres. Collegando più di 3 persone allo stesso
DB postgres dice di avere troppi utenti e si pianta. Forse è pyarchinit che non chiude bene le
connessioni. Dedicheremo 5 giorni per trovare il punto dove pyArchInit non chiude le connessioni.
Se non si ottengono risultati significativi ai test, che possono essere fatti solo in sede adArte snc, si
segnalerà negli issues quanto sistemato e quanto ancora da sistemare. Luca Mandolesi per i test sul
codice.

**Comment by slarosa** [comment]
Ho fatto qualche modifica (5427b401c0d7ef2ee818127b982817562ff3efe7) provando a chiudere correttamente le connessioni aperte al DB, va testata stressando il DB con molte connessioni.

**Comment by slarosa** [comment]
Io lascerei comunque questa issue ancora aperta.

**Comment by slarosa** [comment]
Il branch da testare è [related_issue_36](https://github.com/pyarchinit/pyarchinit/tree/related_issue_36)

**Comment by enzococca** [comment]
per la multiutenza in postgres va settato postgres correttamente. di default postgres da la possibilità di connettersi come 3 super utenti alla volta e di default quando si installa pyarchinit si è super utenti. quindi ho si cambiano i parametri di superutente nel fuile di configurazione di postgres oppure si creano degli utenti con specifiche restrizioni
