### ISSUE TITLE
Scheda US - Errore su navigazione 

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#361]
Debug scheda US – 30/01/2021 Sqlite

1- Prima ancora di aver fatto qualsiasi cosa, cliccando sul tasto “Siti” (connesso a sqlite e senza query di siti attivata).
![immagine](https://user-images.githubusercontent.com/1929829/106479130-416fdc80-64aa-11eb-8e78-b2147d53f4c7.png)

Cliccando su ok compare la solita finestra “non hai settato alcun sito, vuoi settarne uno?” Premendo annulla carica regolarmente le US.

Cliccando su “vai all'ultimo record” da errore python ma poi ci va comunque.

![immagine](https://user-images.githubusercontent.com/1929829/106479197-564c7000-64aa-11eb-9804-0916238f70aa.png)

Stessa cosa ogni volta che si clicca su”vai al primo record”, “avanti di uno”, “indietro di uno”.
In realtà da lo stesso errore praticamente qualsiasi cosa si faccia sulla scheda US, che sia una modifica o premere un tasto qualsiasi: compare due volte l'errore python e poi mi ributta sul canvas. Le modifiche le fa comunque, però come puoi immaginare è una gran bega.

Oggi sabato 30 gennaio 2021 ho debuggato per 1 ora e un quarto, quindi mò ti saluto :-)

**Comment by enzococca** [comment]
problema di database. aggioornare il db
