### ISSUE TITLE
SCHEDE INDIVIDUI

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#362]
SCHEDE INDIVIDUI
Ho compilato tutti i campi da debuggare ad eccezione di quelli della sezione resti osteologici perché non da la possibilità di inserire dati.

![immagine](https://user-images.githubusercontent.com/1929829/106480404-abd54c80-64ab-11eb-9b02-0b2322dbd72e.png)

DATI DESCRITTIVI= il campo osservazione rimane vuoto
ORIENTAMENTO E POSIZIONE=tutti i campi sono stati compilati ma nel pdf compare in tutti none
RESTI OSTEOLOGICI=niente, non è possibile aggiungere resti
ALTRE CARATTERISTICHE= in fase di esportazione compare solo la classe di età e la stima del sesso ma non sono quelli che ho inserito io (che avevo messo femmina e adulto maturo)
TOOLS=non da la possibilità di inserire dati o selezionare cose
P.S. COME SI INDICA L'AZIMUT DI UN INDIVIDUO MORTO?

**Comment by enzococca** [comment]
l'Azimut è l'angolo tra il punto di osservazione(nel nostro caso i piedi del morto) e il nord
