### ISSUE TITLE
Scheda US  TOOLS

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#364]
DATI FISICI SCHEDATORE:

1. Manca la possibilità di inserire da thesaurus i campi: Flottazione, Setacciatura e Affidabilità

TOOLS:

1. Esportazione del matrix:
    a) I rapporti di uguaglianza non vengono messi allo stesso livello. In altre parole due us che sono uguali devono essere posizionate del matrix esattamente sulla stessa linea e non una sopra e una sotto.

b) La possibilità di poter scegliere il colore e la forma dei riquadri delle varie tipologie US è fantastica ma secondo me va migliorata. Prima di tutto toglierei la possibilità di customizare le US contemporanee e le sostituirei con le USM. In seconda istanza tale customizzazione dei colori e forme dei riquadri a mio avviso non funziona correttamente. Esempio pratico. Se vado a customizzare le US negative lui assegna tale forma di box e colore scelti non solo ai tagli ma anche alle us positive tagliate da quei tagli e questo è fuorviante e crea confusione.
La mia necessità è quella di vedere chiaramente quali sono i tagli, quali sono le US positive e quali sono le strutture Stop.

**Comment by enzococca** [comment]
#DATI FISICI SCHEDATORE: fixed
#tools: al momento i rapporti contemporanei non posso essere messi sullo stesso piano. questo è un errore che già esisteva dal pricipio
il matrix è in una fase sperimentale pertanto non verrà toccato. Ad ogni modo c'è la possibilità di esportarlo senza colori e legenda
