### ISSUE TITLE
Avviso ad apertura Qgis

### ISSUE THREAD

**Issue by AgataAgu** [pyarchinit/pyarchinit#371]
Quando vado ad aprire qgis mi appare questa notifica

INFO: Sembra che R non sia installato sul vostro sistema o che non abbiate impostato il percorso in Pyarchinit config. In ogni caso il modulo pyper sarà installato sul vostro sistema, ma non è possibile utilizzare la funzione di archeologia.

Però poi sembra che tutto funzioni ..

**Comment by enzococca** [comment]
Si
É uma avviso che indica che R non é installato
 Non ti preoccupare é in fase di sviluppo servirà per la geostatistica.

Ciao
E

Il mer 3 feb 2021, 18:55 AgataAgu <notifications@github.com> ha scritto:

**Comment by AgataAgu** [comment]
Ok!
Grazie!
