### ISSUE TITLE
Installation error due to ensurepip on Debian and pdf2docx

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#374]
Su Debian/Ubuntu ensurepip è disabilitato, quindi pyArchinit non viene installato.
Se si installano manualmente i moduli non si riesce ad installare pdf2docx perchè il processo di installazione fallisce.

Al di là di capire come aggirare il problema di ensurepip è necessario:
- aggiornare l'elenco dei moduli da installare visibile sul repo di pyArchInit e nel messaggio iniziale: le liste non coincidono.
- eseguire un try except per quei moduli non fondamentali per l'uso di pyArchInit ma accessori: esempio pdf2docx serve solo se si vuole convertire il pdf in doc ma non compromette l'uso del plugin.

**Comment by enzococca** [comment]
fixed
