### ISSUE TITLE
MALFUNZIONAMENTO SCHEDA TOMBA

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#377]
La scheda tomba non registra bene il numero di individuo. In pratica pur inserendolo a mano direttamente nella tomba_table, ogni volta che si riapre l'interfaccia grafica della scheda tomba cancella il valore immesso (vedi foto).
![ELIMINA](https://user-images.githubusercontent.com/10104718/108085620-cf84bf00-7075-11eb-9b13-a0dfcc325727.JPG)

**Comment by enzococca** [comment]
Su che versione stai lavorando?

Il mar 16 feb 2021, 16:41 montarob <notifications@github.com> ha scritto:

**Comment by montarob** [comment]
Sull'ultimo aggiornamento.

Dott. Roberto Montagnetti

Il mar 16 feb 2021, 17:10 enzo <notifications@github.com> ha scritto:

**Comment by enzococca** [comment]
2.3.0?

Il mar 16 feb 2021, 17:49 montarob <notifications@github.com> ha scritto:

**Comment by montarob** [comment]
esatto
