### ISSUE TITLE
PROBLEMA DI INSTALLAZIONE: SYNTAX ERROR EOF VERSIONE 2.3.2

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#399]
Alcuni ragazzi, installando pyarchinit-master versione 2.3.2 hanno avuto questo errore di sintassi e non gli
![elimina](https://user-images.githubusercontent.com/10104718/110023887-fc033100-7d2d-11eb-8d15-89456d56f09e.jpg)
 fà installare il plugin

**Comment by enzococca** [comment]
#398 
cmq risolto nella prossima release
