### ISSUE TITLE
scheda comparazione immagini: non funziona

### ISSUE THREAD

**Issue by enzococca** [pyarchinit/pyarchinit#4]
se si avvia la funzione di comparazione immagini dopo aver scelto il file e la directory da un errore di invalid argument per il file caricato

![capture](https://user-images.githubusercontent.com/3473064/39466590-14208634-4d2a-11e8-8e45-01611fb47ea2.JPG)

**Comment by slarosa** [comment]
@enzococca puoi provare con l'ultima master, anche se non ho idea del perchè si verifica il problema.

**Comment by slarosa** [comment]
@enzococca provato con la master?

**Comment by slarosa** [comment]
@enzococca sei riuscito a provare se nella master il problema è risolto?

**Comment by enzococca** [comment]
Scusami. Il problema persiste ancora

Il Lun 7 Mag 2018, 15:01 Salvatore Larosa <notifications@github.com> ha
scritto:

**Comment by slarosa** [comment]
@enzococca solo per capire e riuscire a riprodurre il problema, mi dici come e cosa dovrebbe fare la scheda comparazioni immagini? Meglio se hai un esempio che posso utilizzare anche io.
Grazie.

**Comment by slarosa** [comment]
ok, potresti provare con l'ultima master, c'era un problema nella lettura dei percorsi alle immagini, ma non so se risolve il problema.
