### ISSUE TITLE
ImportError: No module named 'osgeo' 

### ISSUE THREAD

**Issue by michelesilani** [pyarchinit/pyarchinit#40]
Errore nell'installazione su MacAir - Qgis v. 3.0

File "/Applications/QGIS3.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 664, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'osgeo'

**Comment by pyarchinit** [comment]
Quel modulo è già incluso in QGIS. Come mai non ce l'hai installato?
