### ISSUE TITLE
Problema nel settaggio di Graphviz in impostazioni di sistema

### ISSUE THREAD

**Issue by antoniodambrosio** [pyarchinit/pyarchinit#407]
Non è possibile modificare il percorso di Graphviz in impostazioni di sistema di pyarchinit, il percorso alla cartella rimane bloccato e non modificabile, non permettendo di andare a scegliere il programma installato. La versione installata di Graphviz, che ho installato ieri (2.46.1) non corrisponde alla versione presente nella casella bloccata all'interno di impostazioni di sistema in Graphviz.

**Comment by enzococca** [comment]
Devi disintallare la versione che avevi settato, dopodiché puoi aggiornare
la path graphiz dalla finestra di configurazione parametri di pyarchinit

Il gio 11 mar 2021, 10:58 antoniodambrosio ***@***.***> ha
scritto:
