### ISSUE TITLE
Campo Area in Periodizzazione da rimuovere

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#425]
Nella scheda di periodizzazione è stato aggiunto un campo area che non fa parte degli identificatori di periodo dato che tutte le US di un Sito possono essere collegate al medesimo periodo indipendentemente dall'Area.

Il collegamento tra Scheda US e Periodo avviene su 3 campi: Sito + Periodo + Fase

**Se il campo serve per qualche funzione tipo Matrix è bene specificarlo perchè ingenera confusione e magari posizionarlo in fondo alla scheda.**

La Periodizzazione deve essere identificata da 3 campi + 1 = Sito + Periodo + Fase (+ codice periodo creato in automatico)

La Periodizzazione si lega ( o si può collegare) a 4 schede sulla base di sito+periodo+fase = 

Periodizzazione -> scheda US
Periodizzazione -> Struttura
Periodizzazione -> Tomba 
Periodizzazione -> Individuo

1 Struttura e una Tomba (che è un caso particolare di Struttura) possono essere composte da US che appartengono a più Aree.

L'individuo in teoria appartenendo ad una sola US (sottolineo in teoria) può anche non avere il Periodo-Fase, ma io chiedo di aggiungerli nella versione 3.3 del 2022, in modo da poter fare le distriuzioni individui per periodo e fase.

Per non ingenerare confusione è bene rimuoverlo.

**Comment by enzococca** [comment]
fatto
