### ISSUE TITLE
PROBLEMI PASSAGGIO DA UN SITO ALL'ALTRO ALL'INTERNO DELLO STESSO DB - V. 2.5.7

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#427]
Ho un DB con due siti (vedi foto). 
![errore1](https://user-images.githubusercontent.com/10104718/117148768-d5f21f80-adb6-11eb-9e60-bac848a82ea8.JPG)

Nonostante questo se voglio passare da un DB all'altro, settando nei parametri di connessione la query sul secondo sito, quando vado ad aprire sia la scheda di sito che quella us continua a dirmi che quel sito non esiste nel DB.
![errore1 - b](https://user-images.githubusercontent.com/10104718/117148804-e2767800-adb6-11eb-9aa6-2d5536361119.JPG)

 A quel punto se tiro giù la tendina del nome del sito all'interno della scheda US mi dà un errore di sintassi (vedi foto).

![errore2](https://user-images.githubusercontent.com/10104718/117148836-e99d8600-adb6-11eb-965c-7104dc5ea71c.JPG)

**Comment by enzococca** [comment]
Il problema é l'apice che usi in D'Azeglio. Se lo elimini vedrai che ti
funziona.

Cmq é un bug da risolvere

Il mer 5 mag 2021, 15:31 montarob ***@***.***> ha scritto:

**Comment by montarob** [comment]
Ho cambiato il nome togliendo l'apostrofo, adesso mi setta la query sul secondo sito nella scheda sito ma continua a dirmi che non esiste quel sito nella scheda US

**Comment by enzococca** [comment]
Controlla nella scheda us che non hai salvato con quel nome

Il mer 5 mag 2021, 16:02 montarob ***@***.***> ha scritto:
