### ISSUE TITLE
Errore db pyarchinit Q

### ISSUE THREAD

**Issue by tommasozanca** [pyarchinit/pyarchinit#433]
Seguendo i tutorial su yt, dopo essermi connesso al db pyarchinit_db.sqlite, mi compare questo errore

Il layer non è valido : Il layer dbname='/Users/tommasozanca/pyarchinit/pyarchinit_DB_folder/pyarchinit_db.sqlite' table="pyarchinit_punti_rif" (the_geom) non è valido e non può essere aggiunto alla mappa. Motivo: 

Sto utilizzando QGIS 3.16 da mac

**Comment by enzococca** [comment]
Lasci la suspance?

Il gio 3 giu 2021, 19:04 tommasozanca ***@***.***> ha scritto:

**Comment by tommasozanca** [comment]
Ho editato, ho premuto invio per errore
