### ISSUE TITLE
Non si riesce ad installare pyarchinit

### ISSUE THREAD

**Issue by antoniodambrosio** [pyarchinit/pyarchinit#435]
Buongiorno, ho provato ad installare pyarchinit su computer di Dario, non si riesce ad installare compare errore no module named tkinter e non si riesce ad installare.

**Comment by enzococca** [comment]
Controlla che non abbia altre versioni di pyarchinit installate

Il lun 14 giu 2021, 14:14 antoniodambrosio ***@***.***> ha
scritto:

**Comment by antoniodambrosio** [comment]
Problema risolto, installare l'ultima versione

**Comment by antoniodambrosio** [comment]
E' possibile installare il file tkinter dalla shell dell'osgeo (installer), per l'installazione bisogna selezione advanced  e cercare il file tkinter, dopo di che spuntare sulle due icone e proseguire con l'installazione, la nuova versione di pyarchinit ha risolto questa problematica, quindi non occorre effettuare questo passaggio.

**Comment by enzococca** [comment]
Ottimo.

Il lun 14 giu 2021, 16:30 antoniodambrosio ***@***.***> ha
scritto:
