### ISSUE TITLE
IMPOSSIBILE AGGIUNGERE ALTRI MATERIALI SCHEDA USM 2.6.5

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#441]
Nella scheda USM, sezione tecnica edilizia USM, campo "Materiali" manca il tasto + che permetta di aggiungere più di un materiale.
Questo diventa essenziale in tutti quei paramenti con materiali misti come ad esempio tufo e travertino.

**Comment by enzococca** [comment]
La scheda si riferisce ad una usm per volta quindi quelle usm se è tufo e travertinio dal thesaurus indicherai Tufo/Travertino
