### ISSUE TITLE
Matrix periodizzato non rispetta la query

### ISSUE THREAD

**Issue by monianni** [pyarchinit/pyarchinit#445]
Buongiorno,

segnalo problemi nell'esportazione del Matrix con periodizzazione e con query attiva.
In sostanza, dopo aver inserito ed effettuato il check dei rapporti stratigrafici e dopo aver compilato le voci relative ai vari periodi e fasi (dei quali ho precedentemente creato le apposite schede), effettuo una selezione delle USM in base al quadrante/parete cui appartengono in modo tale da ottenere il Matrix periodizzato relativo al singolo quadrante/parete.
Al momento dell'esportazione, il Matrix si presenta come nell'immagine allegata qui di seguito:

![WhatsApp Image 2021-10-15 at 09 42 43](https://user-images.githubusercontent.com/92514950/137578770-7dc81e8f-a558-4c49-8e07-4868b1b36f7c.jpeg)

In pratica all'interno dei riquadri di periodizzazione compaiono USM appartenenti ad altri quadranti/pareti (esclusi mediante query) che non hanno alcun tipo di rapporto stratigrafico con le USM selezionate e che quindi non avrebbero motivo di comparire nel Matrix. L'unico legame esistente è l'appartenenza al medesimo periodo cronologico ed è come se il Matrix richiamasse tali USM sulla base di questa informazione, ignorando la query e l'assenza di rapporti stratigrafici.

Specifico infine che il problema si presenta solamente se, al momento dell'esportazione del Matrix, aggiungo la periodizzazione; senza periodizzazione selezionata, il Matrix esportato rispetta il criterio stabilito dalla query e si limita ad illustrare i rapporti tra USM appartenenti allo stesso quadrante/parete.

Saluti,
Monica

**Comment by enzococca** [comment]
Ciao, si questo una questione risaputa, ma da un punto di vista metodologico quando si esporta con la periodizzazione si è voluto mantenere il matrix completo, mentre puoi esportare il matrix sotto una ricerca ma senza periodizzazione. Nella nuova release, se hai necessità di avere dei matrix periodizzati facendo una ricerca, potrai farlo con l'implementazione di yed (usato per l'extended matrix).

ciao
E
