### ISSUE TITLE
BUG SCHEDA REPERTI V. 2.6.6.

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#446]
Se inserisci il numero di reperto ad un record, salvi e poi torni indietro ti dà il messaggio che il record è stato modificato e se vuoi confermare o annullare la modifica: se clicchi su OK ti cancella il numero di inventario appena immesso, se dai Annulla NO!
Inoltre appena inserisci un numero di inventario e poi salvi la schermata diventa tutta bianca e devi per forza uscire dalla scheda e rientrare

https://user-images.githubusercontent.com/10104718/140405424-02203995-3ca3-44c0-8d7d-08e895fcbe7b.mp4

.

**Comment by enzococca** [comment]
corretto nella nuova versione
