### ISSUE TITLE
Error method classFactory() - (psycopg2 invalid sslmode value)

### ISSUE THREAD

**Issue by Heryx** [pyarchinit/pyarchinit#448]
Ciao ragazzi, su QGIS 3.22 ho installato PyArchinit da zip, lanciandolo come amministratore. Alla fine del processo di installazione dei pacchetti python mi restituisce questo errore:

**Impossibile caricare il plugin 'pyarchinit-master' a causa di un errore chiamando il metodo classFactory()** 

**sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) invalid sslmode value: "allow?charset=utf8" (Background on this error at: https://sqlalche.me/e/14/e3q8)** 
''
''
''
```
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: invalid sslmode value: "allow?charset=utf8"


The above exception was the direct cause of the following exception:

  File "C:\OSGeo4W\apps\Python39\lib\site-packages\psycopg2\__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) invalid sslmode value: "allow?charset=utf8"

(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

**Comment by enzococca** [comment]
Pyarchinit master non va con qgis 3.22

Il mar 16 nov 2021, 14:35 Giuseppe Guarino ***@***.***> ha
scritto:

**Comment by enzococca** [comment]
fixed into pyarchinit3
