### ISSUE TITLE
COMPORTAMENTO INSOLITO DEL LAYER PYARCHINIT_QUOTE V.3.9.10

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#450]
Attivo la modifica al layer pyarchinit_quote, digitalizzo le varie quote e vedo i punti che sto piazzando, tuttavia quando vado a salvare la modifica spariscono dal canvas anche se l'attributo si è compilato
![Immagine 2022-01-26 133941](https://user-images.githubusercontent.com/10104718/151164568-d8bd0f43-3ff3-47e7-bcf9-e581fac22ae9.png)
.

**Comment by montarob** [comment]
RISOLTO!

**Comment by montarob** [comment]
Sto avendo di nuovo lo stesso comportamento descritto sopra con lo stesso DB!

**Comment by enzococca** [comment]
Aggiorna all ultima versione 3.9.13 e poi fammi sapere

Il sab 2 apr 2022, 19:27 montarob ***@***.***> ha scritto:

**Comment by montarob** [comment]
ok provo...devo aggiornare anche il DB?

**Comment by enzococca** [comment]
Dovrebbe aggiornarsi da solo

Il sab 2 apr 2022, 19:35 montarob ***@***.***> ha scritto:

**Comment by montarob** [comment]
PROBLEMA RISOLTO CON LA VERSIONE 3.9.13
