### ISSUE TITLE
Insufficient privilege

### ISSUE THREAD

**Issue by gianlucamartinez** [pyarchinit/pyarchinit#452]
Problema con il login:
 Eseguo qgis come amministratore, installo pyArchInit su una nuova macchina senza errori. Quando provo a connettermi al database su postgres con le credenziali utente che ho già utilizzato in passato ( e per le quali ho già garantito tutti i permessi per il database) mi spunta il seguente errore: Error: (psycopg2 errors.InsufficientPrivilege) must be owner of table us_table
[SQL: ALTER TABLE us_table ADD COLUMN doc_usv text DEFAULT"]
Per sicurezza ho riconfermato le grant per il mio user ma continuo a ricevere lo stesso errore.
Cambio user per il log in ma l'errore continua a presentarsi. 
![errore 1](https://user-images.githubusercontent.com/84075450/159888313-66c08231-2e5a-48b3-96aa-b1d04f1900b7.jpg)
Per sicurezza ho riconfermato le grant per il mio user ma continuo a ricevere lo stesso errore.

![037fcc2f-8b74-4df0-b5e1-d28df281069b](https://user-images.githubusercontent.com/84075450/159889398-00eace33-4f7a-4936-885b-274b5bb1b6fe.jpg)
L'intera operazione provata su 2 pc diversi e stesso risultato
Se provo ad accedere con lo stesso user da un pc su cui avevo già fatto l'accesso invece non mi da nessun errore
Non so cosa possa essere, grazie in anticipo

**Comment by enzococca** [comment]
Ciao gianluca, grazie per la segnalazione. In questa nuova versione ho
inserito nella us_table un altro campo che servirà per l extended matrix.
Lui sta cercando di installarlo ma deve esserci qualche problema di grant e
non ci riesce. Ora sono in missione in yemen e ritorno a fine mese. Ma per
ovviare al tuo problema prova a connetterti al db postgres via db manager e
su us_table avvia questa sql ALTER TABLE us_table ADD COLUMN doc_usv text
DEFAULT ''

Fammi sapere

Ciao
E

Il gio 24 mar 2022, 13:47 gianlucamartinez ***@***.***> ha
scritto:

**Comment by gianlucamartinez** [comment]
Grazie mille a te, provo subito e faccio sapere

**Comment by enzococca** [comment]
Se non riesci via db manager fallo da pgadmin

Il gio 24 mar 2022, 14:33 gianlucamartinez ***@***.***> ha
scritto:

**Comment by enzococca** [comment]
Poi sei riuscito?

Il gio 24 mar 2022, 13:55 Enzo Cocca ***@***.***> ha scritto:

**Comment by gianlucamartinez** [comment]
Purtroppo il pc su cui ho provato non era il mio e quindi devo organizzarmi per provarci di nuovo. Ho aggiunto il campo doc_usv dal db manager comunque, appena ho sotto mano il pc ci riprovo

Scarica Outlook per Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by enzococca** [comment]
Ciao Gianluca hai risolto? posso chiudere la issue?

**Comment by gianlucamartinez** [comment]
Ciao Enzo, sisi risolto con la query che mi hai detto. Puoi chiudere, grazie mille

Scarica Outlook per Android<https://aka.ms/AAb9ysg>
________________________________
