### ISSUE TITLE
ERRORE COMPILAZIONE E STAMPA CAMPO "TIPO RITUALE" -PyArchinit version: 3.9.14

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#456]
Una volta compilato il Thesaurus relativo alla scheda tomba, quando si va a compilare il campo "Tipo rituale" riporta la sigla e non la sigla estesa.
Ad esempio "INU" anzichè inumazione!

**Comment by enzococca** [comment]
done v.3.9.16
