### ISSUE TITLE
versione 3.9.16 NON FUNZIONA NESSUNA DELLE VIEW

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#457]
Non risultano funzionare le views della scheda US, Scheda struttura, scheda individui e scheda tomba.

**Comment by montarob** [comment]
Errata corrige!...non funziona solamente la view della scheda tomba!

**Comment by enzococca** [comment]
Controlla bene a me funziona.
Se apri la tabella della view tomba essa é riempita?

Il dom 10 apr 2022, 11:32 montarob ***@***.***> ha scritto:
