### ISSUE TITLE
Esportazione Tavole US

### ISSUE THREAD

**Issue by Heryx** [pyarchinit/pyarchinit#46]
Ciao ragazzi,

ho un problema con l'esportazione delle tavole US. 

`File "C:\OSGEO4~1\apps\Python36\lib\site-packages\sqlalchemy\engine\default.py", line 507, in do_execute
              cursor.execute(statement, parameters)
             sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: pyarchinit_quote [SQL: "SELECT * FROM pyarchinit_quote WHERE sito_q = 'Paestum' AND area_q = '1' AND us_q = '600'"] (Background on this error at: http://sqlalche.me/e/e3q8)`

non esiste la tabella pyarchinit_quote. In pratica ho copiato il database pyarchinit_db.sqlite e l'ho rinominato, mettendolo nella stessa cartella di pyarchinit_DB_folder. Però questo database non contiene geometrie e, a quanto pare, nemmeno la tabella quote. Sotto ho anche allegato il messaggio di errore quando connetto il database, su cui ho comunque lavorato popolando le tabelle US, dal Gestore dei Sorgenti Dati.

![immagine](https://user-images.githubusercontent.com/11267377/45805309-bc137500-bcbe-11e8-89d6-5f615922e2a0.jpg)

**Comment by Heryx** [comment]
![immagine2](https://user-images.githubusercontent.com/11267377/45805849-ea458480-bcbf-11e8-83bf-64c319e65a90.jpg)
Come potete vedere il db non contiene i vettori.

**Comment by enzococca** [comment]
Ma che versione stai usando di pyarchinit?

Il Gio 20 Set 2018, 11:23 Giuseppe Guarino <notifications@github.com> ha
scritto:

**Comment by Heryx** [comment]
L'ultima appena scaricata. Ma anche con la precedente mi dava questo problema.
