### ISSUE TITLE
PROBLEMA INSERIMENTO ELEMENTI COSTRUTTIVI - SCHEDA STRUTTURA  - V.3.9.17

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#460]
Non ci sono più i tasti + e - nella sezione "Elementi costruttivi" della scheda di struttura per aggiungere nuovi record
![elimina3](https://user-images.githubusercontent.com/10104718/162688647-d57a6d68-dc78-43ee-8b8d-4b41b962ca0b.jpg)
.

**Comment by montarob** [comment]
Li ho cercati anche in basso ma non ci sono!

**Comment by enzococca** [comment]
fixed v3.9.18
