### ISSUE TITLE
PROBLEMA INSERIMENTO ELEMENTI COSTRUTTIVI - SCHEDA STRUTTURA  - V.3.9.18

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#461]
Il problema in oggetto è stato risolto in questa versione 3.9.18. Tuttavia in molto portatili quei tasti + e - per aggiungere gli elementi costruttivi continuano a non vedersi. Questo a causa dell'eccessiva dimensione (altezza) dell'interfaccia grafica della scheda stessa.
Ad esempio sul mio portatile da 16" non riesco a vederli, ne se riduco manualmente le dimensioni dell'interfaccia ne se cambio le impostazioni di risoluzione dello schermo dalle proprietà.
Riesco a vedere questi tasti solo sullo schermo da 32" di un altro pc che utilizzo.

**Comment by enzococca** [comment]
La risoluzione delle schermo deve essere di 1920x1080

Il gio 14 apr 2022, 10:12 montarob ***@***.***> ha scritto:
