### ISSUE TITLE
QGIS 3.24 da Osgeo4W installer No Module Named Pandas

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#465]
Dopo una installazione pulita di QGIS Pandas non viene installato automanticamente da QGIS ma è necessario scaricarlo manualmente dal repo di OSGEO4w

![immagine](https://user-images.githubusercontent.com/1929829/166256477-f5b7c48f-65cd-49f7-a9e7-8f59e8ef439a.png)

**Comment by enzococca** [comment]
Ok lo aggiungo

Il lun 2 mag 2022, 16:59 Luca Mandolesi ***@***.***> ha
scritto:

**Comment by enzococca** [comment]
fatto
