### ISSUE TITLE
pyArchInit master - Scheda US - non salva i decimali con virgola

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#48]
I campi decimal aggiunti per le misure non salvano i dati con la virgola. Forse è stato lasciata una conversione a string dei numeri.

Verificare!!!!

**Comment by enzococca** [comment]
i campi decimal per le misure non vengono salvati nemmeno con il punto.
error filed fills: SetText (self, str): argument 1 has unexpected type 'decimal.Decimal'
