### ISSUE TITLE
PROBLEMA SCHEDA DI STRUTTURA PyArchinit version: 3.9.18

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#486]
Ogni volta che apri e modifichi la scheda di struttura aggiunge nuovi record VUOTI sia nella sezione dei rapporti che nella sezione degli elementi costruttivi
![ELIMINA](https://user-images.githubusercontent.com/10104718/168883224-b826ee56-7b26-45ce-a985-1642fb2e8b25.jpg)
.

**Comment by enzococca** [comment]
fixed
