### ISSUE TITLE
PROBLEMA ESPORTAZIONE SCHEDA STRUTTURA - V. 4.0.6.

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#498]
Quando vado ad esportare la scheda di struttura, cliccando sul tasto "esporta pdf" non si apre l'interfaccia che mi fa scegliere se esportare le schede o l'elenco o entrambi e quindi non mi fa esportare.
Tuttavia, a volte, continuando a cliccare continuamente sul pulsante, invece tale interfaccia si apre.

**Comment by enzococca** [comment]
fixed
