### ISSUE TITLE
MALFUNZIONAMENTO SCHEDA US V. 4.0.9: NON MANTIENE IL RIFERIMENTO RA QUANDO SI APPORTANO MODIFICHE

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#507]
Ogni volta che si va a modificare un record, se questo contiene un riferimento RA, tale riferimento salta automaticamente e va pertanto reinserito.
Ho notato questa cosa anche riguardo ai Periodi/Fase.

**Comment by enzococca** [comment]
L ultima versione é la 4.1

Il lun 18 lug 2022, 16:57 montarob ***@***.***> ha scritto:
