### ISSUE TITLE
formattazione scheda us

### ISSUE THREAD

**Issue by enzococca** [pyarchinit/pyarchinit#51]
la scheda us deve essere riformattata per una migliore visuale. utilizzando un display 1980x1080, quando apro la scheda us non riesco a ridimensionarla. essa supera la dimensione del mio schermo. inoltre nella sezione usm i campi si accavallano

**Comment by pyarchinit** [comment]
Potrebbe essere una soluzione ridurre di altezza tutti i campi e mettere font 10 o 9 a tutti?

**Comment by enzococca** [comment]
Questa potrebbe essere una soluzione, magari cercando anche un font più
adatto. Ma il problema maggiore è che questa soluzione risolverebbe
problemi di display 1980x1080 ma non quelli inferiori

Il Sab 6 Ott 2018, 11:34 Luca Mandolesi <notifications@github.com> ha
scritto:

**Comment by pyarchinit** [comment]
Proveremo ad aggiungere uno scrolling.
