### ISSUE TITLE
MATRIX NON ESPORTA PIU VERSIONE JPG O PNG V. 4.3.0

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#512]
Ho notato che nella versione 4.3.0 se esporti il matrix non lo esporta più sottoforma di immagine ma solo i file graphml.

**Comment by enzococca** [comment]
No, esporta il jpg e png. Se usi la funzione per EM per esportare il
graphml, esso esporterà un file grpaml.dot per essere convertito in
graphml. Ma non esporterà le immagini dato che dovranno essere processate
in yed

Il mer 27 lug 2022, 12:23 montarob ***@***.***> ha scritto:
