### ISSUE TITLE
thesaurus per "scheda documentazione"

### ISSUE THREAD

**Issue by Gpippo89** [pyarchinit/pyarchinit#522]
Salve in merito alla scheda documentazione volevo chiedere se fosse possibile creare un thesaurus relativo alle voci "tipo documentazione" e "sorgente". Inoltre se fosse possibile inserire un campo relativo al formato del fogli utilizzato.
Per quanto riguarda il campo "tipo documentazione" presente sia nella "scheda documentazione" che nella "scheda US" si potrebbe aggiungere il valore "ICCD - Piante e sezioni" per includere in un unica voce le tavole composite in cui sono contemporaneamente riprodotte sia le piante che le sezioni dell'evidenza? In questo caso spesso mi sono trovato a stampare su un'unica tavola sia le planimetrie dei vari livelli di indagine di una sepoltura, sia la relativa sezione.

Grazie, cordiali saluti
Giuseppe Pippo

**Comment by pyarchinit** [comment]
La scheda documentazione è stata pensata per SCHEDARE LA DOCUMENTAZIONE,
ovvero i documenti grezzi come lucidi, foto rettificate, ortofoto, ecc ecc
ecc..

In teoria quindi 1 sezione 1 tavola che la identifica

Questo serve a pyArchInit per ricreare il dato grezzo

Tuttavia molte volte si consegnano le tavole finali come documentazione e
questo pyArchInit non lo prevede.

Però ormai lo usiamo così.

Sarebbe da fare un convegno tutti insieme per capire cosa rivedere a
livello logico.



Il mer 11 gen 2023, 21:27 enzo ***@***.***> ha scritto:
