### ISSUE TITLE
compilazione campi "responsabile scientifico delle indagini" 

### ISSUE THREAD

**Issue by Gpippo89** [pyarchinit/pyarchinit#523]
Salve ho compilato il tesauros relativo alla "us-table" per creare la voce nella scheda US relativo a "responsabile scientifico delle indagini"  ma all'interno della scheda quando cerco di aprire il menù a tendina non mi dà alcun valore. Nel tesauros ho usato i codici 2.17 "Direttore US" e 2.18 "Responsabile US".
Grazie
Giuseppe Pippo

**Comment by enzococca** [comment]
Ora dovrebbe funzionare

**Comment by Gpippo89** [comment]
Ok grazie

Il mer 25 gen 2023, 18:04 enzo ***@***.***> ha scritto:
