### ISSUE TITLE
issue puntuale tomba

### ISSUE THREAD

**Issue by antoniomanna** [pyarchinit/pyarchinit#524]
Errore sqlite nel momento in cui si inserisce il puntuale tomba gid 1:

Impossibile applicare le modifiche al vettore Tomba

Errori: ERRORE: 1 geometria non aggiunta.
  
  Errori della sorgente dati:
      Errore di SQLite: UNIQUE constraint failed: pyarchinit_tafonomia.gid
    SQL: INSERT INTO "pyarchinit_tafonomia"("the_geom","gid","sito","nr_scheda") VALUES (GeomFromWKB(?, 3004),?,?,?)
![issue_Tomba](https://user-images.githubusercontent.com/74960252/215493885-38b2f94a-e083-464c-b844-2c73c89176a1.PNG)

**Comment by enzococca** [comment]
Che versione di pyarchinit stai usando?prova ad aggiornare il db dalla
scheda settings di pyarchinit.

Fa sapere

Il lun 30 gen 2023, 14:44 antoniomanna ***@***.***> ha
scritto:

**Comment by antoniomanna** [comment]
4.3.9 di PyarchInit e 3.28 di QGIS. Ho aggiornato il DB e continua a darmi lo stesso errore.

**Comment by enzococca** [comment]
Il db lo hai installato dalla versione 4.3.9 oppure stai usando un vecchio
db?

Il lun 30 gen 2023, 15:15 antoniomanna ***@***.***> ha
scritto:

**Comment by antoniomanna** [comment]
Lo ho installato in una versione precedente un mese fa, non ricordo quale, forse la 4.3.3

**Comment by antoniomanna** [comment]
Il problema era dovuto al fatto che avevo creato altri gid del puntuale tomba ma con un altro nome sito (erroneo) percui, non potendoli visualizzare con il layer filtrato, non riuscivo ad individuarli. Ringrazio per la cortese assistenza e mi scuso per la svista. Grazie Enzo.
