### ISSUE TITLE
Scheda US - Pannello Map Preview: non si aggiorna

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#532]
Se si sta sul pannello di preview della mappa us e si scorrono i record, la mappa resta la medesima come se non ricaricasse il poligono dell'US relativa al record

![immagine](https://user-images.githubusercontent.com/1929829/236427757-2c080bbe-c230-4c9e-b6cd-84ddad2c98bf.png)

![immagine](https://user-images.githubusercontent.com/1929829/236428006-e64b2ed3-8808-4334-b4b1-492279a26815.png)

**Comment by enzococca** [comment]
É strano. Che versione stai usando di pyarchinit? Dovrebbe farti vedere il
poligono selezionato riempito e sotto i poligono tratteggiati di tutto lo
scavo.

Fammi sapere

Il ven 5 mag 2023, 11:54 Luca Mandolesi ***@***.***> ha
scritto:

**Comment by pyarchinit** [comment]
Errore mio ... non mi sono accorto di aver compilato male il campo sito... direi di eliminare proprio il ticket...shame on me.
