### ISSUE TITLE
Scheda US - Pannello ricerca avanzata: Apri scheda non funziona

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#533]
Il pannello di Ricerca avanzata ha un pulsante Apri la scheda che non sortisce alcun effetto. Cosa dovrebbe fare?

![immagine](https://user-images.githubusercontent.com/1929829/236782092-904f892e-29db-4e99-aa59-4ec3e18aec69.png)

**Comment by enzococca** [comment]
Apri scheda non é collegato come bottone perché va finita do sviluppare la
funzione. Disabiliterò il comando per il momento

Il lun 8 mag 2023, 10:58 Luca Mandolesi ***@***.***> ha
scritto:

**Comment by enzococca** [comment]
al momento ho disabilitato questa funzione. verrà aggiornata nella release di pyarchinit5
