### ISSUE TITLE
Scheda Documentazione - Aggiungere richiamo a pyunitastratigrafiche

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#537]
Quando si carica da scheda la Documentazione come geometrie, far caricare anche il layer pyunitastratigrafiche in modo che rappresentino la forma grezza della pianta di scavo a partire da una doc (lucido, ortofoto, ecc.).

**Comment by enzococca** [comment]
La scheda documentazione fa apparire le view inerenti al tipo di
documentazione ricercata. Non deve far apparire pyunitastratigrafiche e gli
altri layer perché i layer per il disegno si richiamano solo dalla scheda
sito

Il lun 8 mag 2023, 15:57 Luca Mandolesi ***@***.***> ha
scritto:

**Comment by pyarchinit** [comment]
La scheda documentazione era nata per far vedere il layer pyunitastratigrafiche e mostrare la pianta grezza a partire da una ortofoto,lucido ecc. Fu Chiesto dal funzionario Chiara Guarnieri e lo feci nel 2010. E' molto utile per gli scavi.

**Comment by pyarchinit** [comment]
La query originale di Documentazione: 
![immagine](https://user-images.githubusercontent.com/1929829/236848414-02c6a982-4462-4079-9604-1337045c215f.png)


E come deve apparire: 
![immagine](https://user-images.githubusercontent.com/1929829/236848772-83c9eb14-417b-45cb-89ec-646deb4a9bae.png)
