### ISSUE TITLE
Scheda US - Campi periodizzazione - non carica liste a tendina

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#538]
Al primo avvio della scheda nonostante vi siano record in Periodizzazione non carica le liste a tendina. Serve fare qualcosa perchè le carichi.

**Comment by enzococca** [comment]
fornire maggiori dettagli o il db su cui si sta lavorando. ho fatto vari test su db differenti ma non riesco a riprodurre il tuo errore

**Comment by enzococca** [comment]
Se non ho un esempio per riprodurre l'errore questa issue verrà chiusa. La funzione sembra essere corretta
