### ISSUE TITLE
Tool di importazione

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#540]
IL database di partenza da cui ricava liste a tendina di campi e valori è legato al primo DB che viene segnalato come risorsa. Se si cambia la risorsa i valori restano legati al DB segnalato precedentemente.

In questo esempio caricando un DB legato a Siena, caricando il valore per il sito, Caricando poi un DB diverso relativo all'Oman riappare sempre il valore legato a Siena.

![immagine](https://github.com/pyarchinit/pyarchinit/assets/1929829/bf560c9e-a495-4f1d-9d1f-2cf088ce1d7c)

**Comment by enzococca** [comment]
In realtà c'è una logica. il db di origine è il db a cui si è connessi con pyarchinit in quel momento e quindi il campo nome e valore leggono il db connesso. Si potrebbe usare un db non connesso ma i valori verranno scritti manualmente

**Comment by enzococca** [comment]
quando si carica un db sqlite esso sarà settato come db connesso nei parametri di connessione e si potranno leggere nel campo valore i valori giusti. Per postgres il db di origine dovrà essere sempre il db a cui si è connessi nei parametri di connessione
