### ISSUE TITLE
Scheda US - Campi periodizzazione del primo record compilati in modo errato in automatico

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#544]
Quando si apre la scheda US, i periodi fase iniz e finali sono completati in automatico con il primo valore Periodo Fase, anche se sono già presenti valori precedentemente.

ACCADE SOLO SE NON SI E' SCELTO ALCUN SITO SU CUI BLOCCARE IL SISTEMA, ALTRIMENTI FUZIONA IN MODO CORRETTO.

In questo caso il record era Periodo 2 Fase 1 ma alla riapertura diventa tutto 1, 1, 1, 1.

![immagine](https://github.com/pyarchinit/pyarchinit/assets/1929829/8ffbd374-11a9-402f-8d9f-f3b30ca32079)

**Comment by enzococca** [comment]
problema risolto nella versione v.4.5.8. dammi un feedback
