### ISSUE TITLE
Problemi connessione DB PostgreSQL su server esterno

### ISSUE THREAD

**Issue by stoosh322** [pyarchinit/pyarchinit#549]
Se da QGIS siamo collegati con DB PostgreSQL su server esterno che pyarchinit non è in grado di trovare, QGIS non avvia il plugin.

**Comment by enzococca** [comment]
Devi controllare i settaggi di postgres. Se avvi qgis e il plugin é stato salvato con i parametri di connessione su postgres e il db non é raggiungibile oppure non esiste il plugin non si avvia. Errore noto già da tempo. Cercherò di risolvere appena posso
