### ISSUE TITLE
PROBLEMA TOOL IMPORTAZIONE SCHEDA MATERIALI V. 4.4.5

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#554]
Sto avendo problemi con il tool di importazione nell'importare i record della scheda materiali da un DB all'altro.
Mi da questo problema solo con questa scheda e non ad esempio con la scheda US o scheda sito.
Il messaggio che mi da è "tuple index out of range"
![Cattura](https://github.com/pyarchinit/pyarchinit/assets/10104718/b4d390c8-715d-40c0-86a3-e097912e7405)

**Comment by montarob** [comment]
Ho aggiornato la versione alla 4.4.7 ma continua a darmi lo stesso errore.

**Comment by enzococca** [comment]
Controlla che le tabelle dei due db siano uguali

Il mer 7 giu 2023, 08:03 montarob ***@***.***> ha scritto:

**Comment by enzococca** [comment]
Riaggiorna il plugin (stessa versione 4.4.7)

Il mer 7 giu 2023, 08:06 Enzo Cocca ***@***.***> ha scritto:
