### ISSUE TITLE
ERRORE IMPORTAZIONE GEOMETRIE US DA SPATIALITE A POSTGRES V. 4.5.9

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#557]
Con i tool di importazione volevo importare le geometrie da un DB pyArchinit.sqlite a un DB pyArchinit Postgres ma mi da il seguente errore:
![Cattura](https://github.com/pyarchinit/pyarchinit/assets/10104718/4bebab85-099e-4a62-bcef-2f9aa3ffb7df)

**Comment by enzococca** [comment]
Ha lo stesso sr di riferimento? Il db di destinazione deve essere il db
connesso a pyarchinit



Il mar 27 giu 2023, 16:26 montarob ***@***.***> ha scritto:

**Comment by enzococca** [comment]
Inoltre l'errore del tipo WKB (Well-Known Binary) che stai riscontrando
suggerisce che il database sta ricevendo o tentando di interpretare un tipo
di geometria che non riconosce o supporta. Il numero "24739584" non
corrisponde a nessun tipo standard WKB come definito dal Open Geospatial
Consortium (OGC). I tipi WKB standard includono valori come:

1: Punto
2: Linea
3: Poligono
4: MultiPunto
5: MultiLinea
6: MultiPoligono
7: Collezione Geometrica

La causa sta nel tuo db sqlite in pyunitastratigrafiche. Controlla se le
geometrie sono valide

Il mar 27 giu 2023, 16:29 Enzo Cocca ***@***.***> ha scritto:
