### ISSUE TITLE
PROBLEMA QUERY SITO POSTGRESS V. 4.5.9

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#559]
Sto riscontrando il seguente problema utilizzando pyArchinit con postgres.
Ho inserito un nuovo sito nel DB, a questo punto, dopo aver settato la query sul nuovo sito inserito all'interno della configuarzione del plugin e aver salvato le impostazioni, sono andato ad aprire la scheda US per iniziare la compilazione; tuttavia, la scheda US rimane ancora settata sull'altro sito (quello che c'era in precedenza); questa cosa la fà solamente per la scheda US, infatti se apro la scheda di periodizzazione o di struttura si imposta subito sul nuovi sito inserito.

**Comment by enzococca** [comment]
L ultima versione é la 4.6.0 aggiorna pyarchinit e verifica se hai lo
stesso problema

Il mer 12 lug 2023, 09:28 montarob ***@***.***> ha scritto:

**Comment by montarob** [comment]
Aggiornando la versione alla 4.6.0 il problema è stato risolto.
Grazie Enzo
