### ISSUE TITLE
PyArchinit version: 4.6.0 - NON VISUALIZZA LA US VIEW IN POSTGRES

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#561]
Ho impostato nelle impostazioni di Qgis il percorso agli stili di pyArchinit, tuttavia quando lancio la view in postgres non me la fa visualizzare. Questo nonostante abbia usato delle definizioni già inserite di default all'interno delle regole di stile della view.

**Comment by enzococca** [comment]
E le definizioni nella scheda us sono le stesse dello stile?

Il lun 7 ago 2023, 18:30 montarob ***@***.***> ha scritto:

**Comment by montarob** [comment]
No purtroppo non riesco.

**Comment by montarob** [comment]
Il problema era dato dal fatto che nel layer Unità_Stratigrafiche_Disegno (pyunitastratigrafiche) non era compilato il campo "unità_tipo_s". A differenza di spatialite, dunque, dove tale campo può essere anche tralasciato, se si lavora con pyArchinit all'interno di PostGIS esso deve essere necessariamente compilato per poter visualizzare la view!!!
![elimina](https://github.com/pyarchinit/pyarchinit/assets/10104718/21ba5a3d-d61a-470f-8e6f-d3f6a4f61860)
