### ISSUE TITLE
PROBLEMA ESPORTAZIONE DA SPATIALITE A POSTGRES PYARCHNIT 4.6.1 #567

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#568]
In un DB postgres che contiene due siti, se vado ad importare delle schede US di uno dei due siti prese da un altro DB spatialite mi dà questo errore:
![Cattura4](https://github.com/pyarchinit/pyarchinit/assets/10104718/2a33b2b3-63a6-4243-9d53-3d3f5c6e1b72)

**Comment by montarob** [comment]
Ho provato anche a fare l'importazione manualmente copiando e incollando i vari record da una us_table (spatialite) ad un'altra (postgis) e, nonostante avessi rinumerato gli id_us in modo da non avere doppioni, non mi fà comunque copiare i nuovi record perchè mi dice che l'id_us è già presente.

**Comment by montarob** [comment]
In realtà, sempre usando il tool di importazione me ne importa solamente il 33% del totale

**Comment by enzococca** [comment]
Ciao Roberto.
Sono in arabia saudita appena posso cerco di capire il
Problema

Il ven 6 ott 2023, 16:18 montarob ***@***.***> ha scritto:

**Comment by montarob** [comment]
Grazie Enzo, scusa il disturbo

**Comment by pyarchinit** [comment]
Questo è un campo da 45 caratteri in postgres che su spatialite ne ha presi
di più.

Quale potrebbe essere?


Il ven 6 ott 2023, 15:04 montarob ***@***.***> ha scritto:

**Comment by montarob** [comment]
Non riesca a capirlo ho fatto varie prove riducendo i caratteri nei vari campi stinga.
Inoltre non capisco perchè se importo a mano copiando e incollando dalle due us_table, all'interno di postgres mi dice id_us già esistente (nonostante li abbia pure rinumerati).

**Comment by montarob** [comment]
il problema era dovuto al fatto che andava aggiornata la libreria geoalchemy; inoltre il campo schedatore era troppo lungo per un limite di caratteri dello stesso che è di 45.
