### ISSUE TITLE
IMPOSSIBILITA' DI LASCIARE VUOTO IL CAMPO CRONOLOGIA ALL'INTERNO DELLA SCHEDA PERIODIZZAZIONI

### ISSUE THREAD

**Issue by mattiamaccarinelli** [pyarchinit/pyarchinit#570]
Durante la compilazione della scheda periodizzazione ho notato che risulta impossibile lasciare il campo numerico cronologia (per le datazioni assolute) vuoto. Non essendo ancora sicuro sulle datazioni delle singole fasi avrei preferito lasciare il campo vuoto.
Grazie, ciaoo

**Comment by montarob** [comment]
Buongiorno Mattia,
la scheda di periodizzazione è continuamente aggiornabile, pertanto potrai modificare le datazioni in qualsiasi momento.
