### ISSUE TITLE
Scheda US: modalità trova non funziona con periodo

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#571]
In modalità trova se si cerca un periodo inserito nelle schede non lo trova.
E' possibile che il caricamento datazione letterale nel campo non editabile venga incluso nella ricerca?

**Comment by enzococca** [comment]
In effetti cé un bug legato al compo datazione. Probabilmente perché i due
campi sono connessi.

Proverò a risolvere

E

Il lun 30 ott 2023, 17:46 Luca Mandolesi ***@***.***> ha
scritto:
