### ISSUE TITLE
PROBLEMA CREAZIONE RECORD SCHEDA US PYARCHINIT V. 4.6.2

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#574]
Sto provando a creare nuovi record nella scheda US su database aggiornati con cui ho lavorato fino a pochi giorni fa e mi da questo problema:
![Cattura9](https://github.com/pyarchinit/pyarchinit/assets/10104718/ee21cc4b-1b71-4c90-9662-7ed4a2230e43)

**Comment by montarob** [comment]
Ho provato a creare un nuovo db di prova e a inserire un record e mi da lo stesso problema

**Comment by montarob** [comment]
Da lo stesso problema anche in Postgres

**Comment by Mariagrazia9731** [comment]
Sei riuscito a risolvere? Ho lo stesso problema

**Comment by Mariagrazia9731** [comment]
Sei riuscito a risolvere? Ho lo stesso problema

> Sto provando a creare nuovi record nella scheda US su database aggiornati con cui ho lavorato fino a pochi giorni fa e mi da questo problema: ![Cattura9](https://private-user-images.githubusercontent.com/10104718/283755507-ee21cc4b-1b71-4c90-9662-7ed4a2230e43.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2NDQyMjEsIm5iZiI6MTcwMTY0MzkyMSwicGF0aCI6Ii8xMDEwNDcxOC8yODM3NTU1MDctZWUyMWNjNGItMWI3MS00YzkwLTk2NjItN2VkNGEyMjMwZTQzLkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjAzVDIyNTIwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJjMDcwOWVlYTk3ZDc4ZjAxODQxMDE4Zjg3YTRmOTZkNmRkMjA5ZGQ0YTBmNmQ3ZmMwZDlhOTVlNTAxOTVmODMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bMPMPYE66ym3SvhQ5A26lxRSsvXa-DpGMfm_f6Y1ZHc)

**Comment by montarob** [comment]
Buongiorno,
purtroppo non sono riuscito a risolvere e mi dà lo stesso problema sia in
postgres che spatialite. Al momento, pertanto, ho reinstallato la versione
4.6.1.
*Dott. Roberto Montagnetti PHD*

*Digital and Geomatic Archaeologist, UAV Operator*

*P. IVA: 01574450555 - **PciFA* *10187*

*ARCHEOLOGO - **Fascia I - n. 833* *Elenco Nazionale Archeologi*

Iscrizione *n. 2563* elenco operatori abilitati alla redazione del
documento di valutazione archeologica nel progetto preliminare di opera
pubblica










Il giorno dom 3 dic 2023 alle ore 23:52 Mariagrazia9731 <
***@***.***> ha scritto:
