### ISSUE TITLE
Scheda US campo Struttura: errato caricamento della sigla struttura in modalità ricerca

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#575]
Quando si passa alla modalità ricerca, viene caricata la sigla di struttura inserendo un simbolo '-' tra la sigla letterale e la parte numerica, inficiando la ricerca.

E' stato modificata la formattazione della sigla di struttura ma non è stato aggiornato il database?
La modifica è legata all'extended matrix?

![immagine](https://github.com/pyarchinit/pyarchinit/assets/1929829/5f71b38a-8e67-4ec3-b6c8-bcf60d528ee5)

**Comment by enzococca** [comment]
posso chiudere?

**Comment by pyarchinit** [comment]
Riapriamolo. Meglio togliere questo sistema e fare in modo che scriva ED1 senza trattini. Questo perchè poi lo possiamo sfruttare per fare espressioni regolari e ricavare gli ID usando il primo pacchetto lettere in sigla.
