### ISSUE TITLE
PROBLEMA INSERIMENTO NUOVA SCHEDA US PYARCHINIT 

### ISSUE THREAD

**Issue by Mariagrazia9731** [pyarchinit/pyarchinit#576]
Provando a creare nuovi record nella scheda US su database, mi da un problema: 
Error 2
tuple index out of range
Potreste aiutarmi a risolvere?

**Comment by enzococca** [comment]
Ciao Mariagrazia,
Potresti spiegare il procedimento che hai fatto per produrre questo errore?

In genere quando esce tuple out of range significa che non riesce a trovare
i dati e quindi potrebbe essere corrotto.

Fammi sapere se stai usando un db sqlite o postgres. Nel caso fosse un db
sqlite, tale db deve risiedere dentro la cartella pyarchinit_DB_folder.
Controlla anche il peso del db se è inferiore ai 3-4mega significa che
qualcosa é andato storto.

Ciao
E



Il dom 3 dic 2023, 15:52 Mariagrazia9731 ***@***.***> ha
scritto:

**Comment by Mariagrazia9731** [comment]
Ciao Enzo, 
il db è un db sqlite e si trova nella cartella da te indicata. Anche il peso è corretto (5 mega). 
L'errore mi risulta non appena cerco di salvare un nuovo record di scheda US. Tutto funziona bene se modifico i record già esistenti, ma non appena ne creo uno, compilo i campi necessari e lo salvo, mi compare tale errore. 
![Screenshot 2023-12-03 124559](https://github.com/pyarchinit/pyarchinit/assets/152731088/5441b90c-a86d-4128-8384-1daba93d4368)

**Comment by Mariagrazia9731** [comment]
Sto usando pyarchinit 4.6.2. 
Il db non è stato creato da me, ma mi è stato passato da chi l'ha creato. Penso sia nato da una versione precedente del plugin

**Comment by enzococca** [comment]
Potrebbe essere questo il problema.

Prova a creare un altro db e poi trasferiaci quei file li dentro.

In teoria se il db non è troppo vecchio dovrebbe potersi aggiornare da solo
dopo la prima connessione.

Fa sapere

Ricordati di connettere prima il sito dai parametri di configurazione

E

Il dom 3 dic 2023, 23:25 Mariagrazia9731 ***@***.***> ha
scritto:

**Comment by Mariagrazia9731** [comment]
Ho provato, ma il problema persiste. 
Tuttavia, non credo sia un problema di versione del db perchè altrimenti non mi avrebbe fatto modificare nemmeno le schede create in precedenza da altre persone (cosa che mi ha fatto fare). Il problema esiste solo nella creazione dei nuovi record di schede US

**Comment by enzococca** [comment]
Mandami il tuo db in privato proverò a verificare

Questo errore non riesco a riprodurlo.

Prova a creare un db nuovo e verifica se ti fa inserire i dati

E

Il lun 4 dic 2023, 03:23 Mariagrazia9731 ***@***.***> ha
scritto:

**Comment by pyarchinit** [comment]
Ho appena provato con il "DB DI DEFAULT". Nessun problema con l'ultima versione.

**Comment by enzococca** [comment]
Nemmeno io ho problemi con tutti i miei db anche se ne creo di nuovi

Il lun 4 dic 2023, 18:56 Luca Mandolesi ***@***.***> ha
scritto:

**Comment by Mariagrazia9731** [comment]
Vi ringrazio per i consigli e per le vostre risposte
Stiamo provando ad aggirare il problema o a risolverlo in qualche modo.

**Comment by Mariagrazia9731** [comment]
Grazie! Problema risolto con l'aggiornamento
