### ISSUE TITLE
inserimento all'interno della scheda US di "ente responsabile"

### ISSUE THREAD

**Issue by mattiamaccarinelli** [pyarchinit/pyarchinit#578]
Vorrei inserire l'ente responsabile dello scavo all'interno della scheda US. Nel mio caso sarebbe l'Università di Siena, ma non saprei dove inserirlo; ho provato all'interno del campo "Cod. ente schedatore", ma una volta esportate in pdf le schede US, la casella "ente responsabile" resta vuota. Ci sono anche dei problemi di visualizzazione dell'interfaccia della scheda "dati fisici- dati schedatura". In allegato la foto. Scusatemi e vi ringrazio.
![problema](https://github.com/pyarchinit/pyarchinit/assets/148888821/0fcf714e-70ba-4642-949c-d9b5318d79ae)

**Comment by enzococca** [comment]
Ciao,

per la questione della visualizzazione basta che la parte Localizzazione la chiudi e vedrai che le diciture si riemttono apposto. mentre per il codice ente schedatore è un campo che forse non è agganciato al pdf devo controllare, Ad ogni modo devo questo campo dovrebbe essere numerico o cmq un codice e non è adatto al quello che vorresti tu. Dovresti inserire in responsabile scientifico o responsabile elaborazione.

**Comment by mattiamaccarinelli** [comment]
Ti ringrazio Enzo! 
Allora, le caselle "responsabile scientifico e responsabile elaborazione io le ho compilate, ma sono differenti rispetto a quella di "ente responsabile".  Io intendo proprio la prima casella in alto della prima pagina della scheda US.

**Comment by enzococca** [comment]
aggiornato con la versione 4.6.6
