### ISSUE TITLE
CAMPO SCHEDA US "STATO CONSERVAZIONE" MAX 20 CARATTERI

### ISSUE THREAD

**Issue by mattiamaccarinelli** [pyarchinit/pyarchinit#579]
Buongiorno, 
scusate, se fosse possibile penso sia utile avere a disposizione per il campo "stato conservazione" più di 20 caratteri.

**Comment by pyarchinit** [comment]
Lo stato di conservazione è pensato per valori come pessimo, buono, ottimo
ecc ecc. Non è un campo descrittivo aperto.

Che esempi avevi in mente come valori?


Il mer 13 dic 2023, 09:56 mattiamaccarinelli ***@***.***> ha
scritto:
