### ISSUE TITLE
PROBLEMA INSERIMENTO RECORD SCHEDA TOMBA V. 4.6.8 - POSTGRES

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#580]
Buongiorno,
se inserisco i record della scheda tomba mi da il seguente errore:
Error 1 
(psycopg2.errors.InvalidTextRepresentation) ERRORE:  sintassi di input non valida per il tipo integer: ""
LINE 1: ...'', '', '', '', '', '', '', '', '', '', '[]', '', '', '', ''...
                                                             ^

[SQL: INSERT INTO tomba_table (id_tomba, sito, area, nr_scheda_taf, sigla_struttura, nr_struttura, nr_individuo, rito, descrizione_taf, interpretazione_taf, segnacoli, canale_libatorio_si_no, oggetti_rinvenuti_esterno, stato_di_conservazione, copertura_tipo, tipo_contenitore_resti, tipo_deposizione, tipo_sepoltura, corredo_presenza, corredo_tipo, corredo_descrizione, periodo_iniziale, fase_iniziale, periodo_finale, fase_finale, datazione_estesa) VALUES (%(id_tomba)s, %(sito)s, %(area)s, %(nr_scheda_taf)s, %(sigla_struttura)s, %(nr_struttura)s, %(nr_individuo)s, %(rito)s, %(descrizione_taf)s, %(interpretazione_taf)s, %(segnacoli)s, %(canale_libatorio_si_no)s, %(oggetti_rinvenuti_esterno)s, %(stato_di_conservazione)s, %(copertura_tipo)s, %(tipo_contenitore_resti)s, %(tipo_deposizione)s, %(tipo_sepoltura)s, %(corredo_presenza)s, %(corredo_tipo)s, %(corredo_descrizione)s, %(periodo_iniziale)s, %(fase_iniziale)s, %(periodo_finale)s, %(fase_finale)s, %(datazione_estesa)s)]
[parameters: {'id_tomba': 1, 'sito': 'GDF', 'area': '1', 'nr_scheda_taf': 1, 'sigla_struttura': 'TB', 'nr_struttura': '1', 'nr_individuo': '', 'rito': '', 'descrizione_taf': '', 'interpretazione_taf': '', 'segnacoli': '', 'canale_libatorio_si_no': '', 'oggetti_rinvenuti_esterno': '', 'stato_di_conservazione': '', 'copertura_tipo': '', 'tipo_contenitore_resti': '', 'tipo_deposizione': '', 'tipo_sepoltura': '', 'corredo_presenza': '', 'corredo_tipo': '[]', 'corredo_descrizione': '', 'periodo_iniziale': '', 'fase_iniziale': '', 'periodo_finale': '', 'fase_finale': '', 'datazione_estesa': ''}]
(Background on this error at: https://sqlalche.me/e/14/9h9h)

IN SPATIALITE NON HO QUESTO PROBLEMA!!!

**Comment by enzococca** [comment]
Vedi che forse devi mettere il numero individuo. Prova un attimo.

É un campo che vuole un integer ma non inserendo nulla lo individua come
stringa.

Vedi se é quello

Il gio 14 dic 2023, 16:59 montarob ***@***.***> ha scritto:

**Comment by montarob** [comment]
che proprio non mi fa inserire il numero di individuo (premetto che la scheda di individuo è presente). Ho pensato pure al fatto che si slbocca dopo che hai messo il nome sito, area e n. Scheda e poi salva. Ma se provo cosi, mi dà l'errore scritto in precedenza.
Sembra come se un valore numerico di quelli lo interpreti come stringa, è possibile?

**Comment by pyarchinit** [comment]
Attenzione: spatialite è debolmente tipizzato. Quindi ti fa mettere
stringhe al posto di numeri.... Se passi su postgres poi ti solleva il
problema.

Il gio 14 dic 2023, 14:37 montarob ***@***.***> ha scritto:

**Comment by montarob** [comment]
Infatti penso che sia questo il problema!
