### ISSUE TITLE
Versione 4.6.8 disponibile ma 4.6.7 scaricata dal gestore plugin

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#587]
QGIS 3.28 Firenze

pyarchinit-master rimossa dalla cartella dei plugins e cartella pyarchinit rimossa dalla cartella dell'utente.
Andati su gestisci e installa plugins dava la 4.6.8
Dopo installazione risulta la 4.6.7 con possibilità di aggiornamento alla 4.6.8, ma aggiornando da errore di scompattamento.
Sarà legato alla versione di QGIS?

![immagine](https://github.com/pyarchinit/pyarchinit/assets/1929829/29e1308a-e613-40dc-8189-3a171c462e5a)

**Comment by enzococca** [comment]
Non lo so. Non riesco a capire il motivo



Il ven 15 dic 2023, 20:39 Luca Mandolesi ***@***.***> ha
scritto:
