### ISSUE TITLE
Inserimento dati US pre creata in un DB nuovo - non si chiude il campo SITO e resta modificabile dopo il salva

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#588]
Inserimento dati US pre creata in un DB nuovo - non si chiude il campo SITO e resta modificabile dopo il salva

![immagine](https://github.com/pyarchinit/pyarchinit/assets/1929829/6067ca56-0ce4-4d9f-b245-2e901acbc7df)

**Comment by enzococca** [comment]
É normale se non hai settato il sito. Per rimanere bloccato devi settare il
sito nel file di config

Il ven 15 dic 2023, 21:24 Luca Mandolesi ***@***.***> ha
scritto:
