### ISSUE TITLE
Scheda US, perde il salvataggio dei rapporti v4.6.8 - Errore presente su due macchine in cui è stato necessario riavviare causa errore SIP

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#589]
Dopo aver riempito i due rapporti, al salvataggio perde una US e un numero passa sotto (vedi seconda foto)

![immagine](https://github.com/pyarchinit/pyarchinit/assets/1929829/cba662cd-0157-4d7a-9015-d55ce959f4d1)

![immagine](https://github.com/pyarchinit/pyarchinit/assets/1929829/a0c17b5c-7ccf-42cb-80dd-91894ab5cc71)

**Comment by enzococca** [comment]
In Che versione di qgis si sono verificate questi errori?

Il ven 15 dic 2023, 21:37 Luca Mandolesi ***@***.***> ha
scritto:
