### ISSUE TITLE
Scheda US - Order Layer: in presenza di più scavi nello stesso DB mischia più scavi anche con sito bloccato

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#595]
Scheda US - Order Layer: in presenza di più scavi nello stesso DB mischia più scavi anche con sito bloccato.

Se in UN DB ci sono più scavi, l'order layer non riesce a girare solo su un pacchetto di dati o ricercato, o riferibile a sito del record dai cui viene lanciato, o dal nome del sito della lista a tendina nei tools, o dal sito bloccato a livello di configurazioni.

Inizialmente lavorava solo sul pacchetto SCAVO+AREA, ora sembra averlo perduto.

**Comment by enzococca** [comment]
Ciao Luca, spiegami meglio l errore con un esempio illustrando cosa ti
aspetteresti e cosa invece fa.





Il mer 20 dic 2023, 19:08 Luca Mandolesi ***@***.***> ha
scritto:

**Comment by pyarchinit** [comment]
Deve prendere il sito e l'area dalla lista a tendina sito e area che c'è
sopra al pulsante. Quella usata anche per rapporti stratigrafici per
capirsi e poi lanciare order layer solo su quel pacchetto.

Mi pare che al momento prenda tutti i record in uso in quel momento e se si
hanno più scavi presenti crea paradossi.

Le strade sono 2:

1 - quando si clicca, pyArchInt verifica che in quella istanza non siano
presenti più scavi/area, ma sia tutto omogeneo; se è falso, allora si
chiede all'utente di fare una ricerca di sito/area e poi lanciare il
comando;

2 - usare le liste a tendina sito/area dei tools, col rischio che qualcuno
usi AREA 345   e tale valore non è presente perché è una lista bloccata e
fissa con valori da 1 a 10 mi pare.

Il mer 20 dic 2023, 16:17 enzo ***@***.***> ha scritto:
