### ISSUE TITLE
PROBLEMA IMPORTAZIONE MEDIA - POSTGRES V. 4.6.8

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#600]
Buongiorno,
ho importato attraverso il tool di importazione le seguenti tabelle (MEDIA, MEDIA_THUMB e MEDIATOENTITY) dal DB spatialite a Postgres in modo da poter vedere anche in postgres le varie foto delle US e dei reperti. Tuttavia, se poi apro la scheda US e vado alla sezione MEDIA non vedo nulla. Invece tali foto sono presenti nel Gestore delle immagini, anche se, anche in questo caso, mi sono reso conto che risultano taggate anche ad altri siti dello stesso DBASE (Vedi immagine).
![Cattura12](https://github.com/pyarchinit/pyarchinit/assets/10104718/716c10ed-2644-4e11-ad8f-6e7e67b1b94f)
Per provare a capirne di più ho importato nel pannel layer le tabelle media_thumb e media_to_entity direttamente da Postgres e mi sono reso conto che effettivamente il campo "filepath" mantiene quello del PC da cui proviene lo SPatialite che ho importato. Pertanto non nvorrei che questo sia il problema e che quindi conviene ritaggare tutte le foto dentro Postgres.

**Comment by enzococca** [comment]
Purtroppo al momento se importi i media da un db all'altro c'è un problema
di indicizzazione. Quindi dovresti controllare le immagini che sono
corrette, cancellare quelle che non lo sono e reimportarle. Ricordq che
adesso le foto le inserisci con drag and drop

Il ven 22 dic 2023, 15:15 montarob ***@***.***> ha scritto:

**Comment by enzococca** [comment]
Inoltre la path é relativa nel db. Poi devi settare il percorso dove hai
salvato le immagini nel settings di pyarchinit

Il ven 22 dic 2023, 16:01 Enzo Cocca ***@***.***> ha scritto:
