### ISSUE TITLE
PROBLEMA STAMPA PDF SCHEDE US V. 4.6.8 SPATIALITE 

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#602]
Ho riscontrato un problema anomalo con un db spatialite di uno scavo a cui stavo lavorando.
In pratica se vado a stampare le schede e l'elenco US in pdf mi dà il seguente errore:
Traceback (most recent call last):
  File "C:\Users/Vision 2/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\tabs\US_USM.py", line 4448, in on_pushButton_print_pressed
    data_list = self.generate_list_pdf()
  File "C:\Users/Vision 2/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\tabs\US_USM.py", line 4197, in generate_list_pdf
    quote.sort()
TypeError: '

Versione Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Versione di QGIS: 3.32.3-Lima Lima, 67d46100b5 

A questo punto, ho provato a creare un nuovo DB e a copiare e incollare dentro i dati dal DB vecchio che mi stava dando problemi attraverso il tool di importazione. Tuttavia, ho ancora lo stesso problema!
La cosa strana, però, è che questo errore di stampa inizia a verificarsi solo se importo le geometrie delle quote. Infatti, se io creo un nuovo db e ci importo dentro solo le tabelle e solo le geometrie delle US, lui mi stampa in pdf senza problemi.

**Comment by enzococca** [comment]
Le quote le hai scritte con il punto o con la virgola?

Il gio 11 gen 2024, 12:07 montarob ***@***.***> ha scritto:

**Comment by montarob** [comment]
PROBLEMA RISOLTO AGGIORNANDO IL PLUGIN ALL'ULTIMA VERSIONE 4.6.9
