### ISSUE TITLE
stampa/esportazione pdf schede US DB Pyarchinit

### ISSUE THREAD

**Issue by GiovVerd** [pyarchinit/pyarchinit#603]
Ho un problema di esportazione delle schede US. Problema già segnalato ieri da Roberto Montagnetti che poi lui è riuscito a risolvere installando ultima versione di Pyarchinit. Il DB in questione è lo stesso. Sul mio computer purtroppo anche installando la versione ultima da zip non funziona lo stesso. Non so se è sufficiente quello che ho scritto..........scusa ma è la mia prima  issue. 

Di seguito il testo dell'errore:
Si è verificato un errore durante l'esecuzione del codice Python: 

TypeError: ' 
Traceback (most recent call last):
  File "C:\Users/giovanna/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\tabs\US_USM.py", line 4439, in on_pushButton_print_pressed
    data_list = self.generate_list_pdf()
  File "C:\Users/giovanna/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\tabs\US_USM.py", line 4188, in generate_list_pdf
    quote.sort()
TypeError: '

Versione Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Versione di QGIS: 3.28.6-Firenze Firenze, 868c9fa03b 

Percorso Python:
C:\Users\giovanna\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pyarchinit-master\gui\ui
C:\Users\giovanna\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pyarchinit-master\resources
C:/PROGRA~1/QGIS 3.28.6/apps/qgis-ltr/./python
C:/Users/giovanna/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/giovanna/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS 3.28.6/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS 3.28.6\apps\grass\grass82\etc\python
C:\Windows\System32
C:\PROGRA~1\QGIS 3.28.6\bin\python39.zip
C:\PROGRA~1\QGIS 3.28.6\apps\Python39\DLLs
C:\PROGRA~1\QGIS 3.28.6\apps\Python39\lib
C:\PROGRA~1\QGIS 3.28.6\bin
C:\PROGRA~1\QGIS 3.28.6\apps\Python39
C:\PROGRA~1\QGIS 3.28.6\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS 3.28.6\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS 3.28.6\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS 3.28.6\apps\Python39\lib\site-packages\Pythonwin
C:/Users/giovanna/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\giovanna\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools\tools
C:\Users\giovanna\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\DigitizingTools
C:\Users/giovanna/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master
C:\Users\giovanna\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pyarchinit-master\ext-libs
D:/MeSAP-Lebanon/MeSAP_2023/PIATTAFORMA_GIS_2023

**Comment by enzococca** [comment]
Ciao, controlla che nel layer quote la colonna quote non abbia numeri
interi ma siano con la virgola e poi riprova

Il ven 12 gen 2024, 14:37 GiovVerd ***@***.***> ha scritto:

**Comment by GiovVerd** [comment]
ciao
si l'ultima versione è la 4.9 e ho controllato se  avevo numeri interi.
Avevo una quota senza decimali e l'ho modificata ma non ha risolto la cosa.
Io ho il punto per i decimali e non la virgola comunque. E' giusto così?
Roberto mi ha poi mandato poi  il db che ha ricostituito lui migrando i
vari layers su un db nuovo e ora mi funziona quindi okk per fortuna. Certo
mi rimane la curiosità di capire cosa è successo ma anche non importa....
Grazie moltissime

Il giorno ven 12 gen 2024 alle ore 15:12 enzo ***@***.***> ha
scritto:

**Comment by montarob** [comment]
Ciao Giovanna, a questo punto chiudi la issue per favore.
