### ISSUE TITLE
Rapporti stratigrafici spariti

### ISSUE THREAD

**Issue by colonnellomariachi** [pyarchinit/pyarchinit#604]
QGIS 3.32, PyArchinit 4.6.8, Win11
Modificando o aggiungendo rapporti stratigrafici reciproci ( manualmente, senza l'aggiornamento automatico spuntato) a volte compaiono righe vuote di rapporti stratigrafici. I rapporti sono corretti all'interno del database.

![image](https://github.com/pyarchinit/pyarchinit/assets/6452448/ec7bd9c4-090b-4389-8495-477d7e8bea39)

![image](https://github.com/pyarchinit/pyarchinit/assets/6452448/6196587f-c617-45c3-a72a-b20b32d4e840)

**Comment by montarob** [comment]
Si fa questa cosa ma quando vai a stampare stampa solo i record con i valori, quindi, al di là dell'aspetto estetico, non crea problemi.
