### ISSUE TITLE
NON INSERISCE PIU LA DATAZIONE (LETTERARIA) NELLA SCHEDA US - SPATIALITE V. 4.6.9

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#605]
Compilata la scheda di periodozzazione quando vado ad aggiornare la periodizzazione anche nela scheda US, una volta inserito il numero di Periodo e di Fase non compila più automaticamente il campo datazione (Letteraria) E' come se si fosse perso il collegamento tra la Scheda US e quella di Periodizzazione.
![Cattura](https://github.com/pyarchinit/pyarchinit/assets/10104718/271baac4-02e6-4e33-9e1e-07ef0cffaf0b)

**Comment by enzococca** [comment]
Non inserisce più perché la legge dalla scheda periodo

Il sab 3 feb 2024, 13:23 montarob ***@***.***> ha scritto:

**Comment by montarob** [comment]
Quindi è normale che non la legga la datazione estesa all'interno della
Scheda US?
*Dott. Roberto Montagnetti PHD*

*Digital and Geomatic Archaeologist, UAV Operator*

*P. IVA: 01574450555 - **PciFA* *10187*

*ARCHEOLOGO - **Fascia I - n. 833* *Elenco Nazionale Archeologi*

Iscrizione *n. 2563* elenco operatori abilitati alla redazione del
documento di valutazione archeologica nel progetto preliminare di opera
pubblica










Il giorno sab 3 feb 2024 alle ore 11:42 enzo ***@***.***> ha
scritto:

**Comment by montarob** [comment]
Nella scheda di Periodo c'è la datazione estesa, pero non viene riportata!
![Cattura4](https://github.com/pyarchinit/pyarchinit/assets/10104718/b5f5b372-70d4-47c6-ba2f-80990755bef6)

**Comment by montarob** [comment]
Di conseguenza non viene riportata neanche nella stampa pdf
![Cattura5](https://github.com/pyarchinit/pyarchinit/assets/10104718/c97b1b7b-2cc3-49e3-bad1-376921cf1a3c)

**Comment by pyarchinit** [comment]
Ho fatto togliere dalla scheda US quella datazione in automatico perchè è fuorviante per una serie di motivi. In più c'era un bachetto che faceva inserire nella ricerca quella stringa, rendendo impossibile cercare le cose. Sarebbe caso mai più saggio recuperare dal campo datazione letterale del periodo la stringa, senza ricopiarla in scheda US.

**Comment by montarob** [comment]
Il problema però è che adesso lascia vuoto il campo datazione estesa nel
PDF della scheda us.

Dott. Roberto Montagnetti

Il sab 3 feb 2024, 14:53 Luca Mandolesi ***@***.***> ha
scritto:

**Comment by pyarchinit** [comment]
Posso dire che è un errore riportarla? E spiego il perché: una scheda US
deve avere il periodo e basta.

Poi uno va a vedere la scheda di periodo per la datazione.

Il motivo è ovvio, perché è cartaceo: se di 1000 US p1.1 cambio data,
dovrei rifare tutto il PDF... Se non c'è la datazione invece, cambierei
solo una scheda periodo.

Il sab 3 feb 2024, 16:41 montarob ***@***.***> ha scritto:

**Comment by montarob** [comment]
Si ma al 99% dei casi le schede d Periodizzazione non si consegnano perchè non sono richieste nella consegna della documentazione da parte delle varie SABAP. Ad esempio non devono essere consegnate per gli scavi in concessione, dove si parla solo di Schede US/USM.
Poi a livello estetico è brutto perchè quel campo rimarrebbe vuoto nella stampa pdf. A quel punto bisognerebbe rimodulare anche il modello di stampa pdf. 
Infine, come funzionava prima, mettendo semplicemente il Periodo e la fase, si portava direttamente dentro la datazione estesa. Quindi anche se devi fare una correzione non devi riscrivere a mano la datazione estesa.

**Comment by pyarchinit** [comment]
Il sistema è pensato così perché migliore ovviamente.
Prima metteva una datazione estesa generica che bloccava le ricerche.

È meglio consegnare le schede di periodo e spiegare bene cosa si intende.
Il pulsante è centralizzato allo scopo.

Poi uno può usarlo per i casi particolari, ma il plugin è nato per
migliorare.

Per ora chiudiamo qua e non aggiungiamo la modifica perché purtroppo blocca
tutto il resto.
Appena con Enzo ci mettiamo a tavolino iniziamo a dare le priorità su come
deve essere sistemata questa cosa.

Ciao!


Il lun 5 feb 2024, 16:17 montarob ***@***.***> ha scritto:

**Comment by montarob** [comment]
Per me va pure bene però a sto punto togliamo il campo datazione estesa
nell'esportazione pdf

Il lun 5 feb 2024, 16:45 Luca Mandolesi ***@***.***> ha
scritto:

**Comment by pyarchinit** [comment]
In realtà potrebbero aprirsi nuovi scenari con le AI. C'è caso che ci puoi
fare un replace. Per ora teniamolo li.

Il lun 5 feb 2024, 16:50 montarob ***@***.***> ha scritto:
