### ISSUE TITLE
problema salvataggio modifiche layer

### ISSUE THREAD

**Issue by michaeldipofi** [pyarchinit/pyarchinit#609]
Aprendo il gis e dopo essermi connesso al db se effettuo delle modifiche a layer o ne disegno dei nuovi nel momento in cui salvo spariscono. Il problema lo ho risolto aprendo il gis, connettendomi al db per poi chiudere tutto e riaprire senza effettuare nessuna connessione al db. Facendo così le modifiche ai layer vengono salvate.

**Comment by enzococca** [comment]
Ciao non ho capito di che layer stai parlando. Poi che versione usi di
pyarchinit?

Non credo sia un problema di pyarchinit forse è più probabile di qgis.




Il lun 5 feb 2024, 23:33 michaeldipofi ***@***.***> ha
scritto:

**Comment by michaeldipofi** [comment]
Buonasera, allora come versione di gis ho la 3.22.12, mentre di pyarchinit
la 4.3.3. Infine i layer che non mi salva dopo aver effettuato le modifiche
sono quelli relativi agli ingombri

Il giorno mar 6 feb 2024 alle ore 03:06 enzo ***@***.***> ha
scritto:

**Comment by enzococca** [comment]
Aggiorna alla versione 4.6.9. scarichi lo zip master da github di
pyarchinit e lo installi da zip. Poi fa sapere

Ciao

Il mar 6 feb 2024, 20:16 michaeldipofi ***@***.***> ha
scritto:

**Comment by enzococca** [comment]
Enzo:
Per aggiornare devi prima disattivare il plugin e riavviare qgis

Poi aggiorni da zip

Mi raccomando non aggiornare con il plugin attivo perché mantine la
connessione al db e l'aggiornamento fallisce

Non comporta nessuna perdita di dati ma non ti aggiorna il plugin

Il mar 6 feb 2024, 21:25 Enzo Cocca ***@***.***> ha scritto:
