### ISSUE TITLE
PROBLEMA ESPORTAZIONE PDF SCHEDE ED ELENCO US V. 4.6.9 POSTGRES

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#610]
Buongiorno,
in Postgres, se vado ad esportare in pdf le schede US e l'elenco US non mi stampa e mi dà questo errore:
Si è verificato un errore durante l'esecuzione del codice Python: 

TypeError: ' 
Traceback (most recent call last):
  File "C:\Users/Vision 2/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\tabs\US_USM.py", line 4439, in on_pushButton_print_pressed
    data_list = self.generate_list_pdf()
  File "C:\Users/Vision 2/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\tabs\US_USM.py", line 4188, in generate_list_pdf
    quote.sort()
TypeError: '

Versione Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Versione di QGIS: 3.32.3-Lima Lima, 67d46100b5 

Percorso Python:
C:\Users\Vision 2\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pyarchinit-master\gui\ui
C:\Users\Vision 2\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pyarchinit-master\resources
C:/PROGRA~1/QGIS33~1.3/apps/qgis/./python
C:/Users/Vision 2/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/Vision 2/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~1.3/apps/qgis/./python/plugins
C:\PROGRA~1\QGIS33~1.3\apps\grass\grass83\etc\python
C:\Users\Vision 2\Documents
C:\Program Files\QGIS 3.32.3\bin\python39.zip
C:\PROGRA~1\QGIS33~1.3\apps\Python39\DLLs
C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib
C:\Program Files\QGIS 3.32.3\bin
C:\Users\Vision 2\AppData\Roaming\Python\Python39\site-packages
C:\PROGRA~1\QGIS33~1.3\apps\Python39
C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages
C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.3\apps\Python39\lib\site-packages\Pythonwin
C:/Users/Vision 2/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users/Vision 2/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master
C:\Users\Vision 2\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\pyarchinit-master\ext-libs
C:\Users\Vision 2\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\qfieldsync\libqfieldsync.whl
C:\Users\Vision 2\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins

**Comment by enzococca** [comment]
questo yipo di issue è stata dexcritta già tre volte e in tutti i casi è stata risolta. controlla

#573 #603 #603

**Comment by montarob** [comment]
Questa cosa però rappresenta un problema perchè se la quota è 1 m non posso dargli un valore decimale. Ad ogni modo la fà solo in Postgres.
Inoltre ho modificato tutti i numeri che erano interi ma continua a darmi lo stesso problema.

**Comment by montarob** [comment]
PROBLEMA RISOLTO!
il problema era dato dal fatto che in alcuni record non era stata inserita l'UNITA DI MISURA!
