### ISSUE TITLE
Impossibile caricare il plugin 'pyarchinit-master' a causa di un errore chiamando il metodo classFactory() 

### ISSUE THREAD

**Issue by tommasozanca** [pyarchinit/pyarchinit#611]
Nell'aggiornamento da una vecchia versione ho riscaricato il plugin ma, fin dal primo downolad, ogni volta che apro qgis mi esce questo 

ImportError: dlopen(/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg/cv2/cv2.cpython-39-darwin.so, 0x0002): Library not loaded: @rpath/libprotobuf.22.dylib   Referenced from: /Applications/QGIS-LTR.app/Contents/Resources/python/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg/cv2/cv2.cpython-39-darwin.so   Reason: tried: '/opt/Qt/5.15.2/clang_64/lib/libprotobuf.22.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/Qt/5.15.2/clang_64/lib/libprotobuf.22.dylib' (no such file), '/opt/Qt/5.15.2/clang_64/lib/libprotobuf.22.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/Qt/5.15.2/clang_64/lib/libprotobuf.22.dylib' (no such file), '/Applications/QGIS-LTR.app/Contents/Frameworks/libprotobuf.22.dylib' (no such file), '/Applications/QGIS-LTR.app/Contents/MacOS/lib/libprotobuf.22.dylib' (no such file), '/Applications/QGIS-LTR.app/Contents/Resources/grass78/lib/libprotobuf.22.dylib' (no such file), '/usr/local/lib/libprotobuf.22.dylib' (no such file), '/usr/lib/libprotobuf.22.dylib' (no such file, not in dyld cache) 
Traceback (most recent call last):
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/tommasozanca/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/__init__.py", line 264, in classFactory
    from .pyarchinitPlugin import PyArchInitPlugin
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/tommasozanca/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/pyarchinitPlugin.py", line 28, in 
    from .pyarchinitDockWidget import PyarchinitPluginDialog
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/tommasozanca/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/pyarchinitDockWidget.py", line 31, in 
    from .tabs.Gis_Time_controller import pyarchinit_Gis_Time_Controller
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/tommasozanca/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/tabs/Gis_Time_controller.py", line 36, in 
    from .US_USM import pyarchinit_US
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/tommasozanca/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/tabs/US_USM.py", line 32, in 
    import cv2
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg/cv2/__init__.py", line 5, in 
    from .cv2 import *
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: dlopen(/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg/cv2/cv2.cpython-39-darwin.so, 0x0002): Library not loaded: @rpath/libprotobuf.22.dylib
  Referenced from:  /Applications/QGIS-LTR.app/Contents/Resources/python/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg/cv2/cv2.cpython-39-darwin.so
  Reason: tried: '/opt/Qt/5.15.2/clang_64/lib/libprotobuf.22.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/Qt/5.15.2/clang_64/lib/libprotobuf.22.dylib' (no such file), '/opt/Qt/5.15.2/clang_64/lib/libprotobuf.22.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/Qt/5.15.2/clang_64/lib/libprotobuf.22.dylib' (no such file), '/Applications/QGIS-LTR.app/Contents/Frameworks/libprotobuf.22.dylib' (no such file), '/Applications/QGIS-LTR.app/Contents/MacOS/lib/libprotobuf.22.dylib' (no such file), '/Applications/QGIS-LTR.app/Contents/Resources/grass78/lib/libprotobuf.22.dylib' (no such file), '/usr/local/lib/libprotobuf.22.dylib' (no such file), '/usr/lib/libprotobuf.22.dylib' (no such file, not in dyld cache)
 Versione Python: 3.9.5 (default, Sep 10 2021, 16:18:19) [Clang 12.0.5 (clang-1205.0.22.11)]  Versione di QGIS: 3.28.12-Firenze Firenze, dcc633b2de5 
Percorso Python:
* /Users/tommasozanca/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/gui/ui
* /Users/tommasozanca/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/resources
* /Users/tommasozanca/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/gui/ui
* /Users/tommasozanca/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/resources
* /Users/tommasozanca/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/contour
* /Users/tommasozanca/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/leastcostpath
* /Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python
* /Users/tommasozanca/Library/Application Support/QGIS/QGIS3/profiles/default/python
* /Users/tommasozanca/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
* /Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/plugins
* /Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/numpy-1.20.1-py3.9-macosx-10.13.0-x86_64.egg
* /Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/netCDF4-1.5.4-py3.9-macosx-10.13.0-x86_64.egg
* /Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg
* /Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9
* /Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/pandas-1.3.3-py3.9-macosx-10.13.0-x86_64.egg
* /Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/pyproj-3.2.0-py3.9-macosx-10.13.0-x86_64.egg
* /Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/rasterio-1.1.5-py3.9-macosx-10.13.0-x86_64.egg
* /Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages
* /Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/statsmodels-0.11.1-py3.9-macosx-10.13.0-x86_64.egg
* /Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/GDAL-3.3.2-py3.9-macosx-10.13.0-x86_64.egg
* /Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/scipy-1.5.1-py3.9-macosx-10.13.0-x86_64.egg
* /Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/Pillow-7.2.0-py3.9-macosx-10.13.0-x86_64.egg
* /Users/tommasozanca/Library/Python/3.9/lib/python/site-packages
* /Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/matplotlib-3.3.0-py3.9-macosx-10.13.0-x86_64.egg
* /Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg
* /Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/geopandas-0.8.1-py3.9.egg
* /Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/lib-dynload
* /Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/Rtree-0.9.7-py3.9-macosx-10.13.0-x86_64.egg
* /Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/cftime-1.2.1-py3.9-macosx-10.13.0-x86_64.egg
* /Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/patsy-0.5.1-py3.9.egg
* /Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/Fiona-1.8.13.post1-py3.9-macosx-10.13.0-x86_64.egg
* /Applications/QGIS-LTR.app/Contents/MacOS/lib/python39.zip
* /Users/tommasozanca/Library/Application Support/QGIS/QGIS3/profiles/default/python
* /Users/tommasozanca/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/qfieldsync/libqfieldsync.whl
* /Users/tommasozanca/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/ext-libs
* /Users/tommasozanca/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/shapetools/ext-libs

**Comment by montarob** [comment]
Ciao vai all'interno della cartella di Pyarchinit "pyarchinit_DB_Folder", ed elimina il file "config.cfg". A quel punto riavvia QGIS e non dovresti più avere problemi.

**Comment by tommasozanca** [comment]
Ho provato, ma non cambia nulla

Mac OS versione 14.2.1

QGIS versione 3.28.12
