### ISSUE TITLE
PROBLEMA CON LA VISUALIZZAZIONE ED ESPORTAZIONE DELLA SCHEDA TOMBA. SPATIALITE 4.6.1

### ISSUE THREAD

**Issue by Faberdlm** [pyarchinit/pyarchinit#615]
Una mia collega ha riscontrato questo problema. Non viene più visualizzata la scheda tomba per la sua compilazione. Nel momento in cui si clicca il tasto tomba esce fuori questo messaggio.

![WhatsApp Image 2024-02-19 at 11 28 31](https://github.com/pyarchinit/pyarchinit/assets/160583220/ebbbfe51-c898-46ac-b89e-9f34d39eecfb)
![WhatsApp Image 2024-02-19 at 11 28 53](https://github.com/pyarchinit/pyarchinit/assets/160583220/cf29f463-1638-442f-9e38-05fa0bbac9f5)

Ha creato per prima cosa le schede di struttura relative alle schede tombe. Ha poi creato le schede tombe e quelle individuo. Nel momento in cui ha selezionato l'esportazione delle schede tombe in pdf, ha esportato solo una scheda e dal quel momento non è stato più possibile accedere alla scheda tomba.

**Comment by enzococca** [comment]
Ciao
Il problema è nel database
 É stato salvato un record senza il numero di invetario.

Per ripristinare da db manager ti colleghi al database importi la tabella
tombe_table e inserisci il numero di inventario tomba dove manca.

Salvi e la scheda dovrebbe riapparire. Ti consiglio di aggiornare il plugin
all ultima versione 4.6.9. lo scarichi da GitHub di pyarchinit come zip e
lo installi in qgis come zip. Tieni presente che prima di procede alla
reinstallazione dovrai disattivare il plugin in qgis, riavviare qgis,
disintallare il plugin e reinstallalo come zip.

Spero questo ti aiuti

Ciao
E


Il mar 20 feb 2024, 09:58 Faberdlm ***@***.***> ha scritto:

**Comment by Faberdlm** [comment]
Ciao Enzo,
problema risolto.
Grazie
