### ISSUE TITLE
PROBLEMA VIEW SCHEDA INDIVIDUO V. 4.6.9 SPATIALITE

### ISSUE THREAD

**Issue by montarob** [pyarchinit/pyarchinit#618]
Se lancio la view della scheda individuo, a scherma visualizza correttamente la view attraverso il layer (punto) "individui", ma importa anche una view con geometria poligonale che non c'entra niente con l'individuo. Vedi foto.
![ELIMINA2](https://github.com/pyarchinit/pyarchinit/assets/10104718/c71d00e5-04bd-424b-8f07-f6b0943c5e4e)

**Comment by enzococca** [comment]
No importa l'area poligonale incui sono situate le tombe

Il gio 22 feb 2024, 13:11 montarob ***@***.***> ha scritto:
