### ISSUE TITLE
SCHEDA US errore Esportazione Graphml 

### ISSUE THREAD

**Issue by colonnellomariachi** [pyarchinit/pyarchinit#619]
Quando  dalla scheda us uso il pulsante Esporta in Graphml,  crea un file .xlsx  vuoto da   0 kb e da  il seguente errore:

An error has occurred while executing Python code: 

AttributeError: 'XlsxWriter' object has no attribute 'save' 
Traceback (most recent call last):
  File "C:\Users/Marco/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pyarchinit-master\tabs\US_USM.py", line 4795, in on_pushButton_graphml_pressed
    writer.save()
AttributeError: 'XlsxWriter' object has no attribute 'save'

Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS version: 3.32.2-Lima Lima, c0b8833964 

![image](https://github.com/pyarchinit/pyarchinit/assets/6452448/4d497b74-5298-41e3-b68d-0ce6d510df45)

**Comment by enzococca** [comment]
Che versione di pyarchinit stai usando?



Il ven 8 mar 2024, 16:03 colonnellomariachi ***@***.***> ha
scritto:

**Comment by colonnellomariachi** [comment]
4.6.8

**Comment by enzococca** [comment]
Scarica da github la master che é l'ultima 4.6.9 e installala da zip. Prima
però devi disattivare pyarchinit da qgis riqvviare qgis disinstallare la
vecchia versione installare la nuova versione da zip

Il sab 9 mar 2024, 16:22 colonnellomariachi ***@***.***> ha
scritto:
