### ISSUE TITLE
Impossibile caricare Pyarchinit su MacOs

### ISSUE THREAD

**Issue by Smimo13** [pyarchinit/pyarchinit#620]
Buonasera 
Ho seguito il procedimento vecchio di installazione del Mac.
Credo di aver installato tutti i plugin ma al momento del Plugin da Zip mi si aprono le seguenti finestre
<img width="422" alt="Schermata 2024-03-12 alle 17 21 06" src="https://github.com/pyarchinit/pyarchinit/assets/163164070/f75bf41b-a1e6-440e-8870-fa345fc3a27f">
<img width="422" alt="Schermata 2024-03-12 alle 17 21 22" src="https://github.com/pyarchinit/pyarchinit/assets/163164070/413d6546-5ada-4a4a-bad7-3cf5164a0ad2">

per poi comparire la finestra 

Impossibile caricare il plugin 'pyarchinit-master' a causa di un errore chiamando il metodo classFactory() 

ImportError: dlopen(/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg/cv2/cv2.cpython-39-darwin.so, 0x0002): Library not loaded: '@rpath/libprotobuf.22.dylib'   Referenced from: '/Applications/QGIS-LTR.app/Contents/Resources/python/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg/cv2/cv2.cpython-39-darwin.so'   Reason: tried: '/opt/Qt/5.15.2/clang_64/lib/libprotobuf.22.dylib' (no such file), '/opt/Qt/5.15.2/clang_64/lib/libprotobuf.22.dylib' (no such file), '/Applications/QGIS-LTR.app/Contents/MacOS/../Frameworks/libprotobuf.22.dylib' (no such file), '/Applications/QGIS-LTR.app/Contents/MacOS/lib/libprotobuf.22.dylib' (no such file), '/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/grass78/lib/libprotobuf.22.dylib' (no such file), '/usr/local/lib/libprotobuf.22.dylib' (no such file), '/usr/lib/libprotobuf.22.dylib' (no such file) 
Traceback (most recent call last):
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/erikaalbertini/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/__init__.py", line 264, in classFactory
    from .pyarchinitPlugin import PyArchInitPlugin
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/erikaalbertini/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/pyarchinitPlugin.py", line 28, in 
    from .pyarchinitDockWidget import PyarchinitPluginDialog
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/erikaalbertini/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/pyarchinitDockWidget.py", line 31, in 
    from .tabs.Gis_Time_controller import pyarchinit_Gis_Time_Controller
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/erikaalbertini/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/tabs/Gis_Time_controller.py", line 36, in 
    from .US_USM import pyarchinit_US
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/erikaalbertini/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/tabs/US_USM.py", line 32, in 
    import cv2
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg/cv2/__init__.py", line 5, in 
    from .cv2 import *
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: dlopen(/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg/cv2/cv2.cpython-39-darwin.so, 0x0002): Library not loaded: '@rpath/libprotobuf.22.dylib'
  Referenced from: '/Applications/QGIS-LTR.app/Contents/Resources/python/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg/cv2/cv2.cpython-39-darwin.so'
  Reason: tried: '/opt/Qt/5.15.2/clang_64/lib/libprotobuf.22.dylib' (no such file), '/opt/Qt/5.15.2/clang_64/lib/libprotobuf.22.dylib' (no such file), '/Applications/QGIS-LTR.app/Contents/MacOS/../Frameworks/libprotobuf.22.dylib' (no such file), '/Applications/QGIS-LTR.app/Contents/MacOS/lib/libprotobuf.22.dylib' (no such file), '/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/grass78/lib/libprotobuf.22.dylib' (no such file), '/usr/local/lib/libprotobuf.22.dylib' (no such file), '/usr/lib/libprotobuf.22.dylib' (no such file)

Versione Python: 3.9.5 (default, Sep 10 2021, 16:18:19) [Clang 12.0.5 (clang-1205.0.22.11)] 
Versione di QGIS: 3.34.4-Prizren Prizren, 1e052ed1f5e 

Percorso Python:
/Users/erikaalbertini/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/gui/ui
/Users/erikaalbertini/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/resources
/Users/erikaalbertini/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/gui/ui
/Users/erikaalbertini/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/resources
/Users/erikaalbertini/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/gui/ui
/Users/erikaalbertini/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/resources
/Users/erikaalbertini/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/gui/ui
/Users/erikaalbertini/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/resources
/Users/erikaalbertini/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/gui/ui
/Users/erikaalbertini/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/resources
/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python
/Users/erikaalbertini/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/erikaalbertini/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python39.zip
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/Fiona-1.8.13.post1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/Rtree-0.9.7-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/pandas-1.3.3-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/geopandas-0.8.1-py3.9.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/matplotlib-3.3.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/numpy-1.20.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/Pillow-7.2.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/rasterio-1.1.5-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/GDAL-3.3.2-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/scipy-1.5.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/statsmodels-0.11.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/netCDF4-1.5.4-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/patsy-0.5.1-py3.9.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/lib-dynload
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/pyproj-3.2.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/cftime-1.2.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9
/Users/erikaalbertini/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/erikaalbertini/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/ext-libs

Dove ho sbagliato?

**Comment by Smimo13** [comment]
Aggiungo anche che la mia versione del MacOs è 12.7.4 Monterey e Qgis 3.34.4-Prizren, Python 3.9.5.

**Comment by enzococca** [comment]
Che versione di pyarchinit hai installato?

Il mar 12 mar 2024, 17:34 Smimo13 ***@***.***> ha scritto:

**Comment by Smimo13** [comment]
La versione 4.6.8

**Comment by enzococca** [comment]
Scarica la master zip da github (pulsante verde code). Poi apri qgis
deselezione il plugin pyarchint, riavvia qgis. Disintalli il plugin
pyarchinit e reistalli da zip la master scaricata(4.6.9)

Il mar 12 mar 2024, 17:49 Smimo13 ***@***.***> ha scritto:

**Comment by Smimo13** [comment]
Allora....
Le finestre precedenti non si aprono ma mi dice quest:

Impossibile caricare il plugin 'pyarchinit-master' 

FileNotFoundError: [Errno 2] No such file or directory: '/Applications/QGIS.app/Contents/MacOS/bin/python3' 
Traceback (most recent call last):
  File "/Users/erikaalbertini/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/__init__.py", line 146, in 
    import cv2
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg/cv2/__init__.py", line 5, in 
    from .cv2 import *
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ImportError: dlopen(/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg/cv2/cv2.cpython-39-darwin.so, 0x0002): Library not loaded: '@rpath/libprotobuf.22.dylib'
  Referenced from: '/Applications/QGIS-LTR.app/Contents/Resources/python/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg/cv2/cv2.cpython-39-darwin.so'
  Reason: tried: '/opt/Qt/5.15.2/clang_64/lib/libprotobuf.22.dylib' (no such file), '/opt/Qt/5.15.2/clang_64/lib/libprotobuf.22.dylib' (no such file), '/Applications/QGIS-LTR.app/Contents/MacOS/../Frameworks/libprotobuf.22.dylib' (no such file), '/Applications/QGIS-LTR.app/Contents/MacOS/lib/libprotobuf.22.dylib' (no such file), '/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/grass78/lib/libprotobuf.22.dylib' (no such file), '/usr/local/lib/libprotobuf.22.dylib' (no such file), '/usr/lib/libprotobuf.22.dylib' (no such file)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 401, in loadPlugin
    __import__(packageName)
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 892, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/Users/erikaalbertini/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/__init__.py", line 153, in 
    subprocess.call(["/Applications/QGIS.app/Contents/MacOS/bin/python3", "-m", "pip","install",'opencv-python','--user'])
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/Applications/QGIS.app/Contents/MacOS/bin/python3'


Versione Python: 3.9.5 (default, Sep 10 2021, 16:18:19) [Clang 12.0.5 (clang-1205.0.22.11)] 
Versione di QGIS: 3.34.4-Prizren Prizren, 1e052ed1f5e 

Percorso Python:
/Users/erikaalbertini/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/gui/ui
/Users/erikaalbertini/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/resources
/Users/erikaalbertini/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/gui/ui
/Users/erikaalbertini/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/resources
/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python
/Users/erikaalbertini/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/erikaalbertini/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/numpy-1.20.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python39.zip
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/Fiona-1.8.13.post1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/lib-dynload
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/GDAL-3.3.2-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/geopandas-0.8.1-py3.9.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/rasterio-1.1.5-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/Rtree-0.9.7-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/statsmodels-0.11.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/patsy-0.5.1-py3.9.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/cftime-1.2.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/pyproj-3.2.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/matplotlib-3.3.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/Pillow-7.2.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/netCDF4-1.5.4-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/pandas-1.3.3-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS-LTR.app/Contents/MacOS/lib/python3.9/site-packages/scipy-1.5.1-py3.9-macosx-10.13.0-x86_64.egg
/Users/erikaalbertini/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/erikaalbertini/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master
/Users/erikaalbertini/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master

Cosa manca?

**Comment by enzococca** [comment]
Hai fatto come descritto? Hai disinstallato prima la versione 4.6.8? Il mac
pone sempre dei problemi rispetto alla versione che si usa.

Il mar 12 mar 2024, 18:44 Smimo13 ***@***.***> ha scritto:

**Comment by Smimo13** [comment]
Si ho disinstallato il Plugin 3.6.8 da Qgis.
Devo disintallarlo da Terminale?

**Comment by mattiamaccarinelli** [comment]
buonasera! scusate come avete risolto il problema? Anch'io sto incontrando la stessa problematica.

**Comment by enzococca** [comment]
Hai installato la versione 4.6.9?

Il mer 13 mar 2024, 18:41 mattiamaccarinelli ***@***.***> ha
scritto:

**Comment by mattiamaccarinelli** [comment]
![726281EE-E807-4493-97C7-8D14674E22B2](https://github.com/pyarchinit/pyarchinit/assets/148888821/529ecf4b-827b-41b9-a803-bd7b1442289d)
Si la versione è la 4.6.9. Oltre agli stessi problemi di Smimo13, (class factory) appare un ulteriore errore durante l'installazione. Grazie per la disponibilitá e scusami se rispondo solo ora. Impossibile caricare il plugin '__MACOSX/pyarchinit-master' 

ModuleNotFoundError: No module named '__MACOSX/pyarchinit-master' 
Traceback (most recent call last):
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 404, in loadPlugin
    __import__(packageName)
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named '__MACOSX/pyarchinit-master'


Versione Python: 3.9.5 (default, Sep 10 2021, 16:18:19) [Clang 12.0.5 (clang-1205.0.22.11)] 
Versione di QGIS: 3.36.0-Maidenhead Maidenhead, 09951dc0acf 

Percorso Python:
/Applications/QGIS.app/Contents/MacOS/../Resources/python
/Users/Mattia/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/Mattia/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/netCDF4-1.5.4-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/GDAL-3.3.2-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/cftime-1.2.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pyproj-3.2.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/patsy-0.5.1-py3.9.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numpy-1.20.1-py3.9-macosx-10.13.0-x86_64.egg
/Users/Mattia/.local/lib/python3.9/site-packages
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pandas-1.3.3-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/statsmodels-0.11.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Rtree-0.9.7-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Pillow-7.2.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/geopandas-0.8.1-py3.9.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/rasterio-1.1.5-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/matplotlib-3.3.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python39.zip
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/scipy-1.5.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Fiona-1.8.13.post1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/lib-dynload
/Users/Mattia/Library/Application Support/QGIS/QGIS3/profiles/default/python

**Comment by enzococca** [comment]
Forse non hai disinstallato bene il plugin. Deseleziona pyarchinit da
plugin manager, riavvia qgis, disinstalla pyarchinit e reinstalla

Il ven 15 mar 2024, 11:51 mattiamaccarinelli ***@***.***> ha
scritto:

**Comment by mattiamaccarinelli** [comment]
io ho provato un paio di volte a cancellare la cartella di pyarchinit, la cartella zip pyarchinit master, il plugin in plugin manager, ma il problema rimane.

**Comment by enzococca** [comment]
Controlla nella cartella plugin di qgis che non ci siano due
pyarchinit-master perché dal messaggio sta leggendo un percorso che non
essite. Tipo controlla che non hai una cartella _MACOS

Il ven 15 mar 2024, 12:22 mattiamaccarinelli ***@***.***> ha
scritto:

**Comment by mattiamaccarinelli** [comment]
Ho fatto un po' di prove, inizialmente sembrava che funzionasse nonostante gli avvisi "non collegato a Postgres e graphviz", pyarchinit si era installato ed ero riuscito pure a connettermi al mio DB postgres. Ho provato ad esportare il Matrix con graphviz, ma ho visualizzato l'errore che ho riportato qui sotto. (questa problematica dovrebbe essere colpa mia perchè nonostante io abbia scaricato graphviz non riesco a trovare il file bin.) Purtroppo però una volta chiuso e riaperto Qgis è apparso nuovamente l'avviso classfactory, che quindi non mi consente nemmeno di visualizzare il plugin. In pratica son punto e a capo hahaha
Scusami per le infinite domande, settimana prossima ho più tempo, riproverò tutta la procedura e se dovessi riscontrare gli stessi problemi cercherò di spiegarmi meglio cosí da risolvere più facilmente. 
![C144DDEF-F129-4DC7-B391-4935CD9C6240](https://github.com/pyarchinit/pyarchinit/assets/148888821/1e35b9c9-d72f-4226-92d0-b24d3877fc7d)

Si è verificato un errore durante l'esecuzione del codice Python: 

FileNotFoundError: [Errno 2] No such file or directory: '/Users/Mattia/pyarchinit/pyarchinit_Matrix_folder/matrix_prova.graphml' 
Traceback (most recent call last):
  File "/Users/Mattia/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/tabs/US_USM.py", line 4668, in on_pushButton_graphml_pressed
    with open(output_file, 'r') as file :
FileNotFoundError: [Errno 2] No such file or directory: '/Users/Mattia/pyarchinit/pyarchinit_Matrix_folder/matrix_prova.graphml'


Versione Python: 3.9.5 (default, Sep 10 2021, 16:18:19) [Clang 12.0.5 (clang-1205.0.22.11)] 
Versione di QGIS: 3.36.0-Maidenhead Maidenhead, 09951dc0acf 

Percorso Python:
/Users/Mattia/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/gui/ui
/Users/Mattia/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/resources
/Applications/QGIS.app/Contents/MacOS/../Resources/python
/Users/Mattia/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/Mattia/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/patsy-0.5.1-py3.9.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/cftime-1.2.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/rasterio-1.1.5-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Rtree-0.9.7-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/lib-dynload
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/scipy-1.5.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numpy-1.20.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/GDAL-3.3.2-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python39.zip
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/netCDF4-1.5.4-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/geopandas-0.8.1-py3.9.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pyproj-3.2.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pandas-1.3.3-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Fiona-1.8.13.post1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Pillow-7.2.0-py3.9-macosx-10.13.0-x86_64.egg
/Users/Mattia/.local/lib/python3.9/site-packages
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/matplotlib-3.3.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/statsmodels-0.11.1-py3.9-macosx-10.13.0-x86_64.egg
/Users/Mattia/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/Mattia/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master
/Users/Mattia/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/pyarchinit-master/ext-libs

**Comment by mattiamaccarinelli** [comment]
Buongiorno! 
Scusami per la domanda, io ho installato Graphviz con homebrew (e Graphviz Python module con pip), se ripeto il comando sul terminale mi conferma che Graphviz è installato, però io nelle applicazioni non lo trovo e di conseguenza nemmeno il file bin da associare a pyarchinit nelle impostazioni di sistema.
Grazie scusami

**Comment by enzococca** [comment]
Dovresti trovarlo in /usr/local/bin

Il lun 8 apr 2024, 12:38 mattiamaccarinelli ***@***.***> ha
scritto:

**Comment by mattiamaccarinelli** [comment]
Ci ho guardato, ma nella cartella bin ho solo questi file. 
![IMG_5506](https://github.com/pyarchinit/pyarchinit/assets/148888821/3acd9d2c-2e44-477f-8b63-689dfef548c4)

**Comment by mattiamaccarinelli** [comment]
ho provato, la cartella è la stessa. Scusami Enzo, le sto provando tutte hahaha
ora provo a chiedere anche sul gruppo telegram.
