### ISSUE TITLE
bibliografia schede materiali

### ISSUE THREAD

**Issue by corto81** [pyarchinit/pyarchinit#628]
Buongiorno,
ho scaricato ultima versione pyarchinit 4.7.5, ma in fse di esportazione delle schede di materiale continua a dare problemi per quanto riguarda l'impaginazione del riquadro BIBLIOGRAFIA: il testo fuoriesce dal riquadro e non viene riprodotto nella sua totalità.

Saluti
Fabio

**Comment by enzococca** [comment]
fix it versione master 4.7.6
