### ISSUE TITLE
Errori vari Qgis 3.38 e pyarchinit 3.9.5

### ISSUE THREAD

**Issue by AriannaUccheddu** [pyarchinit/pyarchinit#629]
Ho scaricato la versione di Qgis 3.38, ho scaricato la nuova versione di pyarchinit 3.9.5 ma fuoriescono delle schermate di errore, di seguito le elenco:
- per l'esportazione Matrix: 
TypeError: def_strati_to_rapporti_stratigrafici_check()
- per esportazione di Schede US ed elenchi:
SyntaxError: invalid syntax
-Durante la realizzazione delle schede US:
sqlalchemy.exc. OperationalError (sqlite3. OperationalError) near "opera": syntax error

**Comment by enzococca** [comment]
L 'ultima versione di pyarchinit ê la 4.7.5. devis caricare da qui:
https://github.com/pyarchinit/pyarchinit/archive/refs/heads/master.zip

Il ven 2 ago 2024, 10:01 AriannaUccheddu ***@***.***> ha
scritto:
