### ISSUE TITLE
PROBLEMA ESPORTAZIONE MATRIX PyArchinit version: 4.7.7

### ISSUE THREAD

**Issue by univaq-dsu** [pyarchinit/pyarchinit#636]
se stampo il matrix senza esportazione per EM mi da un'immagine vuota
![Harris_matrix_tred dot](https://github.com/user-attachments/assets/061e76de-c356-4653-9714-860b015888fb)

**Comment by enzococca** [comment]
Devi sempre aggiornare la tavlewidget. Vedi la issue che hai aperto prima

Enzo Cocca PhD
in "Science and Technology for Archaeology and Cultural Heritage"

ISMEO
International Association of Mediterranean and Oriental Studies


mail: ***@***.***
cell: +393495087014



Il giorno ven 4 ott 2024 alle 15:49 univaq-dsu ***@***.***>
ha scritto:

**Comment by enzococca** [comment]
Inoltre aggiorna sempre all ultima versione che al momento è 4.8.3

Enzo Cocca PhD
in "Science and Technology for Archaeology and Cultural Heritage"

ISMEO
International Association of Mediterranean and Oriental Studies


mail: ***@***.***
cell: +393495087014



Il giorno ven 4 ott 2024 alle 16:02 Enzo Cocca ***@***.***> ha
scritto:

**Comment by univaq-dsu** [comment]
Non funzionava perchè non avevo aggiornato i rapporti dalla tablewidget attraverso il comando ctrl+u
