### ISSUE TITLE
PROBLEMI CON CREAZIONE CODICE PERIODO

### ISSUE THREAD

**Issue by matteopucci** [pyarchinit/pyarchinit#65]
Buonasera, sto riscontrando dei problemi (con pyarchinit garibaldi su qgis 3, ma anche con la precedente versione su qgis 2). Quando creo il codice periodo dalla voce "Tools" della scheda US mi compare questo messaggio: 

2018-10-25T23:49:27	1	Traceback (most recent call last):
			  File "C:/Users/matteo/.qgis2/python/plugins\pyarchinit\pyarchinit_US_mainapp.py", line 1528, in on_pushButton_crea_codice_periodo_pressed
			    self.DB_MANAGER.update_cont_per(sito)
			  File "C:/Users/matteo/.qgis2/python/plugins\pyarchinit\modules\db\pyarchinit_db_manager.py", line 886, in update_cont_per
			    self.update('US', 'id_us', [int(i.id_us)], ['cont_per'], [periodiz[0].cont_per])
			IndexError: list index out of range

Come posso risolvere? Grazie mille in anticipo!

**Comment by enzococca** [comment]
Riempi pure le fasi?

Il Gio 25 Ott 2018, 23:54 matteopucci <notifications@github.com> ha scritto:

**Comment by matteopucci** [comment]
Sì, periodi e fasi

**Comment by matteopucci** [comment]
Aggiungo anche che con i siti già presenti nel db questo problema non si presenta. Lo riscontro solo con il sito creato da me

**Comment by enzococca** [comment]
Controlla che tutti siano riempiti. Hai creato le schede di periodizzazione?

Il Ven 26 Ott 2018, 00:02 matteopucci <notifications@github.com> ha scritto:

**Comment by matteopucci** [comment]
Sì ho creato anche le schede di periodizzazione, però effettivamente ho riempito i campi, nelle scede US, solo per gli strati delle diverse fasi del medesimo periodo (il primo). Il problema può essere dovuto al fatto che per le altre US io non abbia ancora definito periodo e fase?

**Comment by pyarchinit** [comment]
La procedura è:

Creare la schede di periodo/fase e assegnare il codice di periodo.

Inserire in tutte le schede US il periodo/fase Iniziale e se richiesto il periodo/fase finale.

Poi creare il codice di continuità periodo.

Attendiamo intanto questo lo chiudo.

**Comment by matteopucci** [comment]
Grazie mille, appena posso faccio la prova!

Il giorno mer 7 nov 2018 alle ore 14:39 Luca Mandolesi <
notifications@github.com> ha scritto:
