### ISSUE TITLE
LOGO - Il logo non viene reinstallato se cancellato da pyarchinit_db_folder

### ISSUE THREAD

**Issue by pyarchinit** [pyarchinit/pyarchinit#69]
Se non è presente il logo.jpg nella cartella pyarchinit/pyarchinit_db_folder, al riavvio pyarchinit non va a copiare il logo per i PDF anche se in pyarchinit_folder_installation è stata aggiunta la seguente funzione a partire dalla riga 85.       

#added by pyarchinit test for logo re-installation
        logo_copy_from_path_rel = os.path.join(os.sep, 'dbfiles', 'logo.jpg')
        logo_copy_from_path = '{}{}'.format(self.RESOURCES_PATH, logo_copy_from_path_rel)
        logo_copy_to_path = '{}{}{}'.format(path, os.sep, 'logo.jpg')
        self.OS_UTILITY.copy_file(logo_copy_from_path, logo_copy_to_path)

**Comment by enzococca** [comment]
mi sembra risolto(?)
