### ISSUE TITLE
scheda pdf export: errore di esportazione

### ISSUE THREAD

**Issue by enzococca** [pyarchinit/pyarchinit#7]
list index out of range
build_Finds_sheets [pyarchinit_exp_Findssheet_pdf.py:633]
__init__ [pyarchinit_exp_Findssheet_pdf.py:139]

**Comment by slarosa** [comment]
da quale scheda si attiva il pulsante?, puoi aggiungere una descrizione di come si esegue l'operazione che da errore? altrimenti faccio fatica, thanks :)

**Comment by enzococca** [comment]
il pulsante si attiva dalla scheda pdf export.
dopo aver fleggato tutte le schede che voglio esportare e avvio il processo da questo errore.

l'errore è per l esportazioni dei reperti

**Comment by enzococca** [comment]
credo che manchi questa riga in pyarchinit_pdf_exp.py
str(self.DATA_LIST[i].repertato)

riga 506

**Comment by slarosa** [comment]
Ma anche sulla 2 non funziona? Giusto?

**Comment by enzococca** [comment]
ok risolto
cambaire in pdf_exp.py così dalla riga 486
def generate_list_reperti_pdf(self):
        data_list = []
        for i in range(len(self.DATA_LIST)):
            data_list.append([
                str(self.DATA_LIST[i].id_invmat),  # 1 - id_invmat
                str(self.DATA_LIST[i].sito),  # 2 - sito
                int(self.DATA_LIST[i].numero_inventario),  # 3 - numero_inventario
                str(self.DATA_LIST[i].tipo_reperto),  # 4 - tipo_reperto
                str(self.DATA_LIST[i].criterio_schedatura),  # 5 - criterio_schedatura
                str(self.DATA_LIST[i].definizione),  # 6 - definizione
                str(self.DATA_LIST[i].descrizione),  # 7 - descrizione
                str(self.DATA_LIST[i].area),  # 8 - area
                str(self.DATA_LIST[i].us),  # 9 - us
                str(self.DATA_LIST[i].lavato),  # 10 - lavato
                str(self.DATA_LIST[i].nr_cassa),  # 11 - nr_cassa
                str(self.DATA_LIST[i].luogo_conservazione),  # 12 - luogo_conservazione
                str(self.DATA_LIST[i].stato_conservazione),  # 13 - stato_conservazione
                str(self.DATA_LIST[i].datazione_reperto),  # 14 - datazione_reperto
                str(self.DATA_LIST[i].elementi_reperto),  # 15 - elementi_reperto
                str(self.DATA_LIST[i].misurazioni),  # 16 - misurazioni
                str(self.DATA_LIST[i].rif_biblio),  # 17 - rif_biblio
                str(self.DATA_LIST[i].tecnologie),  # 18 - misurazioni
                str(self.DATA_LIST[i].tipo),  # 19 - tipo
                str(self.DATA_LIST[i].corpo_ceramico),  # 20 - corpo_ceramico
                str(self.DATA_LIST[i].rivestimento),  # 21 - rivestimento
                str(self.DATA_LIST[i].repertato),  # 22 - repertato
                str(self.DATA_LIST[i].diagnostico)  # 23 - diagnostico
            ])
        return data_list

**Comment by slarosa** [comment]
Urge corso accelerato su git :-)

**Comment by slarosa** [comment]
fixed from #8
